import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { AugmentStat } from '../../src/types';

// Serializes the per-comp augment overlay into src/data/augment-stats.ts. The
// emitted module mirrors the hand-written stub's export surface exactly, so the
// guide's imports keep working whether or not a crawl has run yet.

const here = dirname(fileURLToPath(import.meta.url));
const AUG_PATH = resolve(here, '../../src/data/augment-stats.ts');

const HEADER = `import type { AugmentStat } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN AUGMENT OVERLAY  —  DO NOT HAND-EDIT
//
// Regenerated by the data pipeline (any manual change here is overwritten):
//   • npm run refresh  — crawls the Riot API, tallies which augments each comp
//                        actually ran and how they placed (needs RIOT_API_KEY)
//
// Keyed by comp id. Each comp maps to its top augments by real pick rate, with
// the placement they produced. A missing key (or empty array) means "no crawled
// augment data yet" — the guide then falls back to the archetype priorities in
// comps.ts rather than inventing numbers.
// ---------------------------------------------------------------------------`;

const FOOTER = `/** Real crawled augments for a comp, best (lowest avg place) first; [] when none yet. */
export function augmentsForComp(compId: string): AugmentStat[] {
  return COMP_AUGMENT_STATS[compId] ?? [];
}`;

/** Write the augment overlay module. Pass an empty record to reset it to the stub. */
export function writeAugmentStatsFile(byComp: Record<string, AugmentStat[]>, source: string): string {
  const hasData = Object.keys(byComp).length > 0;
  const updatedAt = hasData ? new Date().toISOString() : '';
  const body = hasData ? JSON.stringify(byComp, null, 2) : '{}';

  const file = `${HEADER}

export const COMP_AUGMENT_STATS: Record<string, AugmentStat[]> = ${body};

/** When the augment overlay was last regenerated (empty until the first crawl). */
export const AUGMENT_STATS_UPDATED_AT = ${JSON.stringify(updatedAt)};
/** Provenance string for the overlay (empty until the first crawl). */
export const AUGMENT_STATS_SOURCE = ${JSON.stringify(hasData ? source : '')};

${FOOTER}
`;

  writeFileSync(AUG_PATH, file, 'utf8');
  return AUG_PATH;
}
