import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { Contested } from '../../src/types';

// Performance numbers for one comp, written into src/data/stats.ts.
export interface CompStats {
  avgPlace: number;
  top4: number; // %
  first: number; // %
  contested: Contested;
  sampleSize: number; // # of classified boards behind these numbers
}

const here = dirname(fileURLToPath(import.meta.url));
const STATS_PATH = resolve(here, '../../src/data/stats.ts');

const HEADER = `import type { Contested } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN PERFORMANCE OVERLAY  —  DO NOT HAND-EDIT
//
// Regenerated by the data pipeline; any manual change here is overwritten:
//   • npm run import   — apply numbers from a hand-filled JSON (no API key)
//   • npm run refresh  — crawl the Riot API and recompute (needs RIOT_API_KEY)
//
// Overrides ONLY the four performance fields of each comp; all structural data
// (units, traits, carries, items…) stays hand-authored in comps.ts. An empty
// record means "use the seed numbers in comps.ts".
// ---------------------------------------------------------------------------

export interface CompStats {
  avgPlace: number;
  top4: number; // %
  first: number; // %
  contested: Contested;
  sampleSize: number;
}`;

// Serialize the stats map + provenance into a typed stats.ts module.
export function writeStatsFile(stats: Record<string, CompStats>, source: string): string {
  const updatedAt = new Date().toISOString();
  const body = Object.keys(stats).length === 0 ? '{}' : JSON.stringify(stats, null, 2);

  const file = `${HEADER}

export const COMP_STATS: Record<string, CompStats> = ${body};

export const STATS_UPDATED_AT: string | null = ${JSON.stringify(updatedAt)};

export const STATS_SOURCE: string | null = ${JSON.stringify(source)};
`;

  writeFileSync(STATS_PATH, file, 'utf8');
  return STATS_PATH;
}
