import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { ChampionStats } from '../../src/types';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, '../../src/data/champion-stats.ts');

const HEADER = `import type { ChampionStats } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN CHAMPION OVERLAY  —  DO NOT HAND-EDIT
//
// Per-champion Double Up performance, keyed by the normalized champion id in
// champions.ts (e.g. "missfortune"). Regenerated by the data pipeline:
//   • npm run refresh:champions  — crawl the Riot API and recompute (needs RIOT_API_KEY)
//
// An empty record means "no champion data yet" — the UI shows units from the
// catalog with their stats columns blank until the crawl populates this file.
// ---------------------------------------------------------------------------`;

// Serialize the champion-stats map + provenance into a typed module. An empty
// map writes null timestamps/source so the UI's "no data yet" branch stays put.
export function writeChampionStatsFile(stats: Record<string, ChampionStats>, source: string): string {
  const hasData = Object.keys(stats).length > 0;
  const body = hasData ? JSON.stringify(stats, null, 2) : '{}';
  const updatedAt = hasData ? new Date().toISOString() : null;

  const file = `${HEADER}

export const CHAMPION_STATS: Record<string, ChampionStats> = ${body};

export const CHAMPION_STATS_UPDATED_AT: string | null = ${JSON.stringify(updatedAt)};

export const CHAMPION_STATS_SOURCE: string | null = ${JSON.stringify(hasData ? source : null)};
`;

  writeFileSync(OUT, file, 'utf8');
  return OUT;
}
