import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { UnitMath, ItemMath, TraitMath } from '../../src/types';

// Serializes the extracted theorycraft math into src/data/unit-math.ts. Keys
// are sorted so reruns produce stable diffs (clean CI commits).

const here = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(here, '../../src/data/unit-math.ts');

const HEADER = `import type { UnitMath, ItemMath, TraitMath } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN UNIT MATH  —  DO NOT HAND-EDIT
//
// Faithful raw numbers behind Set 17 champions, items, and traits, extracted
// from CommunityDragon (no API key). Regenerated by:
//   • npm run build:math
//
// Input to the deterministic combat model (src/lib/combat-model). UNIT_MATH and
// ITEM_MATH are keyed by apiName; TRAIT_MATH is keyed by display name (matching
// how comps + the catalog reference traits). Ability variable \`value\` arrays
// are indexed by star level: value[1]=1★, value[2]=2★, value[3]=3★ (index 0 is
// a cdragon placeholder; high indices are often junk).
// ---------------------------------------------------------------------------`;

const FOOTER = `export const ALL_UNITS: UnitMath[] = Object.values(UNIT_MATH);
export const ALL_ITEMS: ItemMath[] = Object.values(ITEM_MATH);
export const ALL_TRAITS: TraitMath[] = Object.values(TRAIT_MATH);

/** Raw math for a unit by apiName (e.g. "TFT17_MissFortune"). */
export function unitMath(apiName: string): UnitMath | undefined {
  return UNIT_MATH[apiName];
}
/** Stat effects for a completed item by apiName. */
export function itemMath(apiName: string): ItemMath | undefined {
  return ITEM_MATH[apiName];
}
/** Breakpoint tiers for a trait by DISPLAY name (e.g. "Challenger"). */
export function traitMath(name: string): TraitMath | undefined {
  return TRAIT_MATH[name];
}`;

export function writeUnitMathFile(
  data: { units: UnitMath[]; items: ItemMath[]; traits: TraitMath[] },
  source: string,
): string {
  const units: Record<string, UnitMath> = {};
  for (const u of [...data.units].sort((a, b) => a.apiName.localeCompare(b.apiName))) units[u.apiName] = u;
  const items: Record<string, ItemMath> = {};
  for (const i of [...data.items].sort((a, b) => a.apiName.localeCompare(b.apiName))) items[i.apiName] = i;
  const traits: Record<string, TraitMath> = {};
  for (const t of [...data.traits].sort((a, b) => a.name.localeCompare(b.name))) traits[t.name] = t;

  const file = `${HEADER}

export const UNIT_MATH: Record<string, UnitMath> = ${JSON.stringify(units, null, 2)};

export const ITEM_MATH: Record<string, ItemMath> = ${JSON.stringify(items, null, 2)};

export const TRAIT_MATH: Record<string, TraitMath> = ${JSON.stringify(traits, null, 2)};

/** When this module was last regenerated. */
export const UNIT_MATH_UPDATED_AT = ${JSON.stringify(new Date().toISOString())};
/** Provenance string. */
export const UNIT_MATH_SOURCE = ${JSON.stringify(source)};

${FOOTER}
`;

  writeFileSync(OUT_PATH, file, 'utf8');
  return OUT_PATH;
}
