import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import type { AbilityFormula } from '../../src/types';

// Serializes Stage 3 ability formulas into src/data/ability-formulas.ts. Keys
// are sorted so reruns produce stable diffs (clean CI commits).

const here = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(here, '../../src/data/ability-formulas.ts');

const HEADER = `import type { AbilityFormula } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN ABILITY FORMULAS  —  DO NOT HAND-EDIT
//
// Stage 3 of the theorycraft engine. Each entry pins an exact per-cast BASE
// damage for a unit's ability — the structural combination of its raw cdragon
// variables (multi-cast cycles averaged, per-hit × hit count, DoT totals) that
// the name-only heuristic in combat-model can't infer from variable names.
//
//   \`expression\`   the human/Claude-supplied STRUCTURE (arithmetic over the
//                  ability's variable names).
//   \`perCastBase\`  that expression evaluated per star OFFLINE. The runtime
//                  reads ONLY these numbers — it never parses the string.
//
// Regenerated by:
//   • npm run build:formulas                            (manual + authored seed — no key)
//   • CLAUDE_CODE_OAUTH_TOKEN=… npm run build:formulas  (CI: Claude fills rest — subscription, free)
//   • ANTHROPIC_API_KEY=… npm run build:formulas        (CI: Claude fills rest — metered API)
//
// perCastBase is in the SAME native units as the variables, BEFORE AP/AD
// scaling and item amp — the combat model applies those downstream unchanged.
// Indexed by star: perCastBase[1]=1★, [2]=2★, [3]=3★ (mirrors unit-math).
// ---------------------------------------------------------------------------`;

const FOOTER = `export const ALL_FORMULAS: AbilityFormula[] = Object.values(ABILITY_FORMULAS);

/** Pinned per-cast formula for a unit's ability by apiName, if one exists. */
export function abilityFormula(apiName: string): AbilityFormula | undefined {
  return ABILITY_FORMULAS[apiName];
}`;

export function writeAbilityFormulasFile(formulas: AbilityFormula[], source: string): string {
  const map: Record<string, AbilityFormula> = {};
  for (const f of [...formulas].sort((a, b) => a.apiName.localeCompare(b.apiName))) map[f.apiName] = f;

  const file = `${HEADER}

export const ABILITY_FORMULAS: Record<string, AbilityFormula> = ${JSON.stringify(map, null, 2)};

/** When this module was last regenerated. */
export const ABILITY_FORMULAS_UPDATED_AT = ${JSON.stringify(new Date().toISOString())};
/** Provenance string. */
export const ABILITY_FORMULAS_SOURCE = ${JSON.stringify(source)};

${FOOTER}
`;

  writeFileSync(OUT_PATH, file, 'utf8');
  return OUT_PATH;
}
