import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { discoverBoards } from '../src/lib/theorycraft';
import { UNIT_MATH_SOURCE } from '../src/data/unit-math';

// ---------------------------------------------------------------------------
// Stage 2 of the theorycraft engine: run the (expensive) trait-anchored beam
// search OFFLINE and bake the discovered high-synergy boards into
// src/data/theorycraft.ts. The app stays 100% static — discovery never runs in
// the browser; the client just renders these baked results (and can re-derive
// each board's math live via the cheap combat-model).
//
//   npm run build:theorycraft
//
// Pure on top of the keyless unit-math, so this needs no Riot/Anthropic key and
// runs locally or in CI. "Theorycraft proposes, ladder data validates" — these
// are candidates to cross-check against the Double Up crawl, not gospel.
// ---------------------------------------------------------------------------

const TOP_N = 24;

const here = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(here, '../src/data/theorycraft.ts');

const HEADER = `import type { BoardScore } from '../lib/theorycraft';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN THEORYCRAFT DISCOVERIES  —  DO NOT HAND-EDIT
//
// High-synergy 8-unit boards discovered by the deterministic combat model's
// trait-anchored beam search (src/lib/theorycraft). Regenerated by:
//   • npm run build:theorycraft
//
// Ranked by a blended score (trait DEPTH + top-2 carry DPS + top-3 frontline
// EHP). This is a CANDIDATE GENERATOR — the math proposes, the crawled Double Up
// ladder data validates — so treat novel boards as leads to test, not as a meta.
// ---------------------------------------------------------------------------`;

// Round floats for clean, stable diffs; integer counts pass through untouched.
const round = (_k: string, v: unknown): unknown =>
  typeof v === 'number' && !Number.isInteger(v) ? Math.round(v * 1000) / 1000 : v;

function main(): void {
  console.log('Discovering high-synergy boards (offline beam search)…');
  const t0 = Date.now();
  const boards = discoverBoards({ topN: TOP_N });
  const secs = ((Date.now() - t0) / 1000).toFixed(1);

  const file = `${HEADER}

export const DISCOVERED_BOARDS: BoardScore[] = ${JSON.stringify(boards, round, 2)};

/** When the discovery search was last run. */
export const THEORYCRAFT_UPDATED_AT = ${JSON.stringify(new Date().toISOString())};
/** Provenance of the underlying unit math the search ran on. */
export const THEORYCRAFT_SOURCE = ${JSON.stringify(UNIT_MATH_SOURCE)};
`;
  writeFileSync(OUT_PATH, file, 'utf8');

  console.log('\n──────── theorycraft summary ────────');
  console.log(`discovered: ${boards.length} boards`);
  for (const b of boards.slice(0, 8)) {
    const top = b.activeTraits.find((t) => t.tierLevel > 0);
    const id = top ? `${top.name} ${top.count}` : 'no breakpoint';
    console.log(`  score ${b.score.toFixed(1)}  [${id}]  carry ${b.suggestedCarry}`);
  }
  console.log(`\n✓ wrote ${OUT_PATH}  (${secs}s)`);
}

try {
  main();
} catch (e) {
  console.error(`✖ build:theorycraft failed: ${(e as Error).message}`);
  process.exitCode = 1;
}
