import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { fetchCdragon, assetUrl, normalizeName, SET_MUTATOR } from './lib/cdragon';

// ---------------------------------------------------------------------------
// Generate src/data/champions.ts (the champion CATALOG) from CommunityDragon.
// No API key. Run after a set/patch drops:
//
//   npm run champions
//
// Writes the structural catalog only (id, name, cost, traits, art). Per-champion
// PERFORMANCE comes separately from the Double Up crawl into champion-stats.ts.
// ---------------------------------------------------------------------------

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, '../src/data/champions.ts');

async function main(): Promise<void> {
  const { champions } = await fetchCdragon();

  const seen = new Set<string>();
  const rows = champions
    .map((c) => ({
      id: normalizeName(c.apiName),
      apiName: c.apiName,
      name: c.name,
      cost: c.cost,
      traits: c.traits,
      portrait: assetUrl(c.tileIcon),
      splash: assetUrl(c.squareIcon),
    }))
    .filter((r) => (seen.has(r.id) ? false : (seen.add(r.id), true)))
    .sort((a, b) => a.cost - b.cost || a.name.localeCompare(b.name));

  const body =
    `// AUTO-GENERATED by scripts/build-champions.ts — DO NOT EDIT BY HAND.\n` +
    `// Source: CommunityDragon TFT (${SET_MUTATOR}). Regenerate with: npm run champions\n` +
    `import type { Champion } from '../types';\n\n` +
    `export const CHAMPIONS_SET = 'Set 17';\n` +
    `export const CHAMPIONS_UPDATED_AT = ${JSON.stringify(new Date().toISOString())};\n\n` +
    `export const CHAMPIONS: Champion[] = ${JSON.stringify(rows, null, 2)};\n`;

  writeFileSync(OUT, body);

  console.log(`✓ wrote ${rows.length} champions → ${OUT}`);
  for (const cost of [1, 2, 3, 4, 5]) {
    const names = rows.filter((r) => r.cost === cost).map((r) => r.name);
    console.log(`  ${cost}-cost (${names.length}): ${names.join(', ')}`);
  }
}

main().catch((e) => {
  console.error(`✖ build-champions failed: ${(e as Error).message}`);
  process.exitCode = 1;
});
