// ---- Core domain types ----
export type DamageType = 'AD' | 'AP' | 'hybrid';
export type Playstyle = 'aggressive' | 'scaling'; // aggressive = early tempo, scaling = econ/late
export type Tempo = 'reroll' | 'fast8' | 'tempo';
export type Contested = 'low' | 'moderate' | 'high' | 'severe';

export interface Carry {
  name: string;
  damageType: DamageType;
  items: string[];
}

export interface Comp {
  id: string;
  name: string;
  traits: string[];
  carries: Carry[];
  frontline: string[];
  units: string[]; // ALL units in the comp — used for overlap detection
  primaryDamage: DamageType; // dominant item component type for this comp
  playstyle: Playstyle;
  tempo: Tempo;
  levelStrategy: string; // human-readable, e.g. "Lvl 6 reroll", "Fast 8"
  contested: Contested;
  avgPlace: number;
  top4: number; // %
  first: number; // %
  augments: string[]; // archetype guidance, not exact names
}

// ---- Comp guide: positioning + augments ----
/** One unit placed on the board. row 0 = front line (engages first), row 3 = backline; col 0..6. */
export interface BoardSlot {
  unit: string; // catalog DISPLAY name — matches Comp.units / catalog `name`
  row: number; // 0 (front) .. 3 (back)
  col: number; // 0 .. 6
}

/** A recommended augment for a comp, backed by real crawled Double Up data. */
export interface AugmentStat {
  id: string; // Riot augment apiName, e.g. "TFT17_Augment_DarkStarHeart"
  name: string; // display name
  icon: string; // icon URL (CommunityDragon)
  tier: AugmentTier | null; // augment slot rarity; null when cdragon doesn't encode it
  pickRate: number; // % of this comp's boards that ran it
  avgPlace: number; // team-scale avg place (1..4) when taken
  top4: number; // % top-4 when taken
  n: number; // boards observed
}
export type AugmentTier = 'silver' | 'gold' | 'prismatic';

// ---- User preferences ----
export type PlaystylePref = Playstyle | 'any';
export type TempoPref = 'reroll' | 'fast8' | 'any';
export type ItemLean = 'AD' | 'AP' | 'flexible';
export type ContestedTolerance = 'avoid' | 'balanced' | 'fight';

export interface Prefs {
  playstyle: PlaystylePref;
  tempo: TempoPref;
  itemLean: ItemLean;
  contested: ContestedTolerance;
}

export const DEFAULT_PREFS: Prefs = {
  playstyle: 'any',
  tempo: 'any',
  itemLean: 'flexible',
  contested: 'balanced',
};

// ---- Champion catalog (generated from CommunityDragon) ----
export interface Champion {
  id: string; // normalized key, joins to ChampionStats — e.g. "missfortune"
  apiName: string; // Riot apiName, e.g. "TFT17_MissFortune"
  name: string;
  cost: number; // 1..5
  traits: string[]; // display names
  portrait: string; // square HUD icon URL (grid tiles)
  splash: string; // splash-tile URL (detail hero)
}

// ---- Per-champion Double Up performance (machine overlay) ----
export interface ChampionItemStat {
  name: string;
  icon: string;
  pct: number; // % of this champion's itemized boards carrying the item
}
export interface ChampionCompStat {
  id: string; // comp id from comps.ts
  name: string;
  n: number; // boards of this champion that classified into the comp
}
export interface ChampionStats {
  avgPlace: number; // team scale 1..4
  top4: number; // % top half (top 2 of 4 teams)
  first: number; // % won (on the 1st-place team)
  pickRate: number; // % of Double Up boards that field this unit
  sampleSize: number; // boards observed with this unit
  bestItems: ChampionItemStat[];
  bestComps: ChampionCompStat[];
}

// Catalog entry merged with its optional stats (null = no data yet).
export interface ChampionView extends Champion {
  stats: ChampionStats | null;
}

// ---- Theorycraft math layer (extracted from CommunityDragon, no key) ----
// Faithful raw numbers behind champion abilities, items, and traits — the
// deterministic inputs to the combat model. Regenerated by `npm run build:math`.

/** Base combat stats for a unit (cdragon values; crit chance as 0..1). */
export interface UnitBaseStats {
  hp: number;
  armor: number;
  magicResist: number;
  damage: number; // base attack damage
  attackSpeed: number; // attacks per second
  critChance: number; // 0..1
  critMultiplier: number; // e.g. 1.4
  mana: number; // mana required to cast
  initialMana: number; // mana at combat start
  range: number; // hexes
}

/** How an ability scales, read deterministically from the cdragon desc icons
 *  (%i:scaleAP% / %i:scaleAD%). 'mixed' = both, 'none' = flat/utility. */
export type AbilityScaling = 'AP' | 'AD' | 'mixed' | 'none';

/** One ability variable. `value` is indexed by star level: value[1]=1★,
 *  value[2]=2★, value[3]=3★ (index 0 is a cdragon placeholder; high indices
 *  are often junk/unobtainable-tier values). */
export interface AbilityVariable {
  name: string;
  value: number[];
}

export interface UnitAbilityMath {
  name: string;
  scaling: AbilityScaling;
  /** Raw cdragon tooltip template, with @Variable@ placeholders and %i:scale…%
   *  markers intact. The only source of ability STRUCTURE — how the variables
   *  actually combine (per-hit vs total, "every N casts" cycles, DoT-over-
   *  duration) — which the variable names alone don't encode. Consumed offline
   *  by the Stage 3 formula layer; never parsed at runtime. */
  desc: string;
  variables: AbilityVariable[];
}

/** A Stage 3 ability interpretation: the offline Claude layer reads the raw
 *  `desc` + variables and emits an arithmetic `expression` over the variable
 *  names that yields the per-cast BASE damage (in the same native units the
 *  combat model's largest-variable heuristic used, so AP/AD scaling + damageAmp
 *  apply downstream unchanged). The expression is evaluated OFFLINE per star
 *  into `perCastBase`; the runtime reads only numbers — it never evals a string.
 *  This supersedes the name-only multi-hit / DoT heuristics for units it covers. */
export interface AbilityFormula {
  apiName: string; // join key (unit apiName)
  ability: string; // ability display name (sanity check vs unit-math)
  expression: string; // arithmetic over this ability's variable names + constants
  scaling: AbilityScaling; // which stat the per-cast base scales by, read from desc
  perCastBase: number[]; // expression evaluated per star (mirrors AbilityVariable.value indexing)
  dotDuration?: number; // >0 ⇒ perCastBase is a total spread over this many seconds
  trueDamage?: boolean; // true damage ignores resists (the sim skips mitigation)
  rationale: string; // one line, grounded in the description
  source: 'manual' | 'claude'; // hand-verified seed vs offline-generated
  model?: string; // Claude model id when source==='claude'
}

/** A playable unit and the raw math behind it. */
export interface UnitMath {
  apiName: string; // "TFT17_MissFortune"
  name: string;
  cost: number; // 1..5
  traits: string[]; // trait DISPLAY names (join to TraitMath / comps)
  stats: UnitBaseStats;
  ability: UnitAbilityMath;
}

/** A completed Set 17 combat item and its stat modifiers. Keys are mostly
 *  human-readable (AP, CritChance, …); a few are opaque cdragon hashes.
 *  null-valued effects are dropped at extraction. */
export interface ItemMath {
  apiName: string;
  name: string;
  effects: Record<string, number>;
}

/** One trait breakpoint tier and the bonuses it grants (null vars dropped). */
export interface TraitTierMath {
  minUnits: number;
  maxUnits: number; // 25000 = top/unbounded tier
  variables: Record<string, number>;
}
export interface TraitMath {
  apiName: string;
  name: string;
  tiers: TraitTierMath[];
}
