import type { AbilityFormula } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN ABILITY FORMULAS  —  DO NOT HAND-EDIT
//
// Stage 3 of the theorycraft engine. Each entry pins an exact per-cast BASE
// damage for a unit's ability — the structural combination of its raw cdragon
// variables (multi-cast cycles averaged, per-hit × hit count, DoT totals) that
// the name-only heuristic in combat-model can't infer from variable names.
//
//   `expression`   the human/Claude-supplied STRUCTURE (arithmetic over the
//                  ability's variable names).
//   `perCastBase`  that expression evaluated per star OFFLINE. The runtime
//                  reads ONLY these numbers — it never parses the string.
//
// Regenerated by:
//   • npm run build:formulas                          (manual seed — no key)
//   • ANTHROPIC_API_KEY=… npm run build:formulas      (CI: Claude fills rest)
//
// perCastBase is in the SAME native units as the variables, BEFORE AP/AD
// scaling and item amp — the combat model applies those downstream unchanged.
// Indexed by star: perCastBase[1]=1★, [2]=2★, [3]=3★ (mirrors unit-math).
// ---------------------------------------------------------------------------

export const ABILITY_FORMULAS: Record<string, AbilityFormula> = {
  "TFT17_Fiora": {
    "apiName": "TFT17_Fiora",
    "ability": "Perfect Bladework",
    "expression": "NumVitals * VitalDamage",
    "scaling": "AD",
    "perCastBase": [
      300,
      222,
      336,
      4662,
      4662,
      4662,
      4662
    ],
    "rationale": "Active strikes all NumVitals vitals, each for VitalDamage true damage (AD); the AP half is only the heal.",
    "source": "manual",
    "trueDamage": true
  },
  "TFT17_Sona": {
    "apiName": "TFT17_Sona",
    "ability": "Psionic Crush",
    "expression": "(4 * DebrisDamage + DebrisRipDamage + SlamDamage) / NumCasts",
    "scaling": "AP",
    "perCastBase": [
      272.5,
      408,
      616,
      2998.8,
      3199,
      2.1,
      2.1
    ],
    "rationale": "Rip+slam every 5th cast (DebrisRipDamage+SlamDamage); the other 4 deal DebrisDamage — averaged over NumCasts.",
    "source": "manual"
  }
};

/** When this module was last regenerated. */
export const ABILITY_FORMULAS_UPDATED_AT = "2026-06-03T01:29:36.901Z";
/** Provenance string. */
export const ABILITY_FORMULAS_SOURCE = "manual+seed-only";

export const ALL_FORMULAS: AbilityFormula[] = Object.values(ABILITY_FORMULAS);

/** Pinned per-cast formula for a unit's ability by apiName, if one exists. */
export function abilityFormula(apiName: string): AbilityFormula | undefined {
  return ABILITY_FORMULAS[apiName];
}
