import type { AbilityFormula } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN ABILITY FORMULAS  —  DO NOT HAND-EDIT
//
// Stage 3 of the theorycraft engine. Each entry pins an exact per-cast BASE
// damage for a unit's ability — the structural combination of its raw cdragon
// variables (multi-cast cycles averaged, per-hit × hit count, DoT totals) that
// the name-only heuristic in combat-model can't infer from variable names.
//
//   `expression`   the human/Claude-supplied STRUCTURE (arithmetic over the
//                  ability's variable names).
//   `perCastBase`  that expression evaluated per star OFFLINE. The runtime
//                  reads ONLY these numbers — it never parses the string.
//
// Regenerated by:
//   • npm run build:formulas                            (manual + authored seed — no key)
//   • CLAUDE_CODE_OAUTH_TOKEN=… npm run build:formulas  (CI: Claude fills rest — subscription, free)
//   • ANTHROPIC_API_KEY=… npm run build:formulas        (CI: Claude fills rest — metered API)
//
// perCastBase is in the SAME native units as the variables, BEFORE AP/AD
// scaling and item amp — the combat model applies those downstream unchanged.
// Indexed by star: perCastBase[1]=1★, [2]=2★, [3]=3★ (mirrors unit-math).
// ---------------------------------------------------------------------------

export const ABILITY_FORMULAS: Record<string, AbilityFormula> = {
  "TFT17_Aatrox": {
    "apiName": "TFT17_Aatrox",
    "ability": "Stellar Slash",
    "expression": "DamageAD + DamagePercentArmor",
    "scaling": "mixed",
    "perCastBase": [
      201,
      81.8,
      122.7,
      184.05,
      306.9,
      603,
      603
    ],
    "rationale": "The tooltip's single physical damage number is tagged with both %i:scaleAD% and %i:scaleArmor%, combining the flat DamageAD component with the armor-scaling DamagePercentArmor component; healing (HealHP/HealAP) is ignored and the conditional TFT17_DRX capstone NOVA strike is excluded as a set-specific augment effect.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Akali": {
    "apiName": "TFT17_Akali",
    "ability": "Star Strike",
    "expression": "NumShurikens * DamageAD",
    "scaling": "AD",
    "perCastBase": [
      135,
      195,
      295,
      440,
      750,
      360,
      360
    ],
    "rationale": "NumShurikens kunai, each DamageAD to the first target hit — all land on a lone target.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_AurelionSol": {
    "apiName": "TFT17_AurelionSol",
    "ability": "Deathbeam",
    "expression": "DamagePerSecond * Duration",
    "scaling": "AP",
    "perCastBase": [
      750,
      1005,
      1515,
      6000,
      6000,
      4950,
      4950
    ],
    "rationale": "Channel: DamagePerSecond magic damage each second over Duration(3)s — the total spread across the beam.",
    "source": "claude",
    "dotDuration": 3,
    "model": "claude-opus-4.7"
  },
  "TFT17_Aurora": {
    "apiName": "TFT17_Aurora",
    "ability": "Hopped-Up Hacks",
    "expression": "Damage + SplitDamage",
    "scaling": "AP",
    "perCastBase": [
      5.5,
      480,
      720,
      1150,
      1990,
      5.5,
      5.5
    ],
    "rationale": "Each cast deals flat magic damage to the target plus a separate magic damage pool split among all enemies hit, both scaling with AP; the true-damage stored-damage payoff depends on damage from all sources over the hack duration, not just this spell, so it isn't part of the spell's own base damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Bard": {
    "apiName": "TFT17_Bard",
    "ability": "Ultra Friendly Object",
    "expression": "DamagePerSecond * Duration",
    "scaling": "AP",
    "perCastBase": [
      8,
      960,
      1440,
      12000,
      20000,
      8,
      8
    ],
    "rationale": "Saucer hits the target for DamagePerSecond each second over Duration(4)s — the total spread across its lifetime.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Belveth": {
    "apiName": "TFT17_Belveth",
    "ability": "Tidal Slashes",
    "expression": "BaseNumSlashes * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      600,
      264,
      396,
      600,
      1020,
      0,
      0
    ],
    "rationale": "BaseNumSlashes slashes (base count; grows with AS), each ADDamage physical to the target — all land on a lone target.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Blitzcrank": {
    "apiName": "TFT17_Blitzcrank",
    "ability": "Party Crasher",
    "expression": "UppercutDamage + ExplosionDamage",
    "scaling": "AP",
    "perCastBase": [
      370,
      325,
      490,
      5999,
      7000,
      5789,
      10000
    ],
    "rationale": "The knocked-up target takes both UppercutDamage and the ExplosionDamage crash; the heuristic keeps only the larger half.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Briar": {
    "apiName": "TFT17_Briar",
    "ability": "Fish Frenzy",
    "expression": "ADDamage + APDamage",
    "scaling": "mixed",
    "perCastBase": [
      3.3,
      130,
      195,
      310,
      530,
      3.3,
      3.3
    ],
    "rationale": "Fish Frenzy's active deals ModifiedDamage physical damage that combines a flat AD-scaled base (ADDamage) with an AP-scaled component (APDamage), while the tank bonus is conditional on target type and not averaged into base damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Caitlyn": {
    "apiName": "TFT17_Caitlyn",
    "ability": "Aim For The Head",
    "expression": "(ProcChance * (Damage + BonusDamage)) / 100",
    "scaling": "mixed",
    "perCastBase": [
      24.75,
      31.5,
      47.25,
      87.75,
      150.3,
      77.25,
      77.25
    ],
    "rationale": "Each attack has a ProcChance% chance to deal a Headshot combining AD-scaled Damage and AP-scaled BonusDamage, so average damage per attack is the proc-chance-weighted sum of the two components.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Chogath": {
    "apiName": "TFT17_Chogath",
    "ability": "Accretion",
    "expression": "BonusDamage",
    "scaling": "AP",
    "perCastBase": [
      140,
      210,
      290,
      420,
      715,
      450,
      450
    ],
    "rationale": "Total damage is BonusDamage (AP-scaling) plus 8% of the target's current max health, but no target-health variable is provided so only the flat BonusDamage component can be expressed.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Corki": {
    "apiName": "TFT17_Corki",
    "ability": "Asteroid Blaster",
    "expression": "BaseMissiles * MissileAD * (1 + ProcChance / 100 * (ProcDamageMult - 1))",
    "scaling": "AD",
    "perCastBase": [
      787.5,
      882,
      1323,
      8820,
      6300,
      787.5,
      787.5
    ],
    "rationale": "BaseMissiles missiles at MissileAD each (all land on a lone target), with the ProcChance mega-missile (ProcDamageMult×) folded in as expected value.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Diana": {
    "apiName": "TFT17_Diana",
    "ability": "Pale Cascade",
    "expression": "NumAttacks * BaseDamage",
    "scaling": "AP",
    "perCastBase": [
      150,
      180,
      270,
      480,
      810,
      720,
      990
    ],
    "rationale": "Each cast summons NumAttacks (3) orbs that each deal BaseDamage magic damage (scales with AP) to enemies they pass through; the passive attack bonus is a separate always-on effect, not part of the cast.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Ezreal": {
    "apiName": "TFT17_Ezreal",
    "ability": "Temporal Shot",
    "expression": "ADDamage + APDamage + DroneDamage/TakedownsToDrone",
    "scaling": "mixed",
    "perCastBase": [
      0,
      185.143,
      277.714,
      414.571,
      708.286,
      0,
      0
    ],
    "rationale": "Base cast deals AD+AP physical damage, and drone damage (AD-scaling) is averaged in since a drone is gained every TakedownsToDrone takedowns and fires on cast.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Fiora": {
    "apiName": "TFT17_Fiora",
    "ability": "Perfect Bladework",
    "expression": "NumVitals * VitalDamage",
    "scaling": "AD",
    "perCastBase": [
      300,
      222,
      336,
      4662,
      4662,
      4662,
      4662
    ],
    "rationale": "Active strikes all NumVitals vitals, each for VitalDamage true damage (AD); the AP half is only the heal.",
    "source": "manual",
    "trueDamage": true
  },
  "TFT17_Fizz": {
    "apiName": "TFT17_Fizz",
    "ability": "Meep Bait",
    "expression": "DashDamage + (BiteDamageAP / 3)",
    "scaling": "AP",
    "perCastBase": [
      113.333,
      201.667,
      303.333,
      458.333,
      731.667,
      470,
      470
    ],
    "rationale": "Dash deals DashDamage magic damage every cast, and every third cast also deals BiteDamageAP magic damage from the Mega Meep, so it's averaged over the 3-cast cycle; both scale with AP per the tooltip markers.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Gnar": {
    "apiName": "TFT17_Gnar",
    "ability": "Slingshot Maneuver",
    "expression": "(DamageAD + DamageAP) / 5",
    "scaling": "mixed",
    "perCastBase": [
      46,
      49,
      74,
      121,
      187,
      139,
      139
    ],
    "rationale": "The boomerang's ModifiedDamage (scaling both AD and AP) only fires on every 5th attack, so its damage is averaged over that 5-attack cycle; the conditional Meep Bonus DPS is a separate augment-gated mechanic, not the base passive damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Gragas": {
    "apiName": "TFT17_Gragas",
    "ability": "Chemical Rage",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      0,
      200,
      300,
      450,
      765,
      0,
      0
    ],
    "rationale": "Chemical Rage deals a single instance of Damage magic damage (scales with AP) to the target and adjacent enemies after the heal resolves.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Graves": {
    "apiName": "TFT17_Graves",
    "ability": "Collateral Damage",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      400,
      390,
      585,
      5555,
      5555,
      5555,
      5555
    ],
    "rationale": "The shell's on-target Damage is physical %i:scaleAD%; the heuristic mis-reads the neutral name as AP. Same number, correct AD scaling.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Gwen": {
    "apiName": "TFT17_Gwen",
    "ability": "Dance n' Dice",
    "expression": "Damage + AreaDamage",
    "scaling": "AP",
    "perCastBase": [
      300,
      220,
      330,
      625,
      1065,
      1260,
      1260
    ],
    "rationale": "One cast deals Damage magic damage to the primary target plus AreaDamage to enemies in the cone, both scaling with AP; the on-kill reset cast is conditional and not a guaranteed part of the base cast.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Illaoi": {
    "apiName": "TFT17_Illaoi",
    "ability": "Test of Spirit",
    "expression": "HealthDrain + Damage",
    "scaling": "AP",
    "perCastBase": [
      120,
      135,
      205,
      310,
      415,
      480,
      480
    ],
    "rationale": "Sums the AP-scaled true-damage Health drain dealt over the 3s duration and the AP-scaled magic damage from the slam, both marked with %i:scaleAP%.",
    "source": "claude",
    "dotDuration": 3,
    "model": "claude-cli"
  },
  "TFT17_IvernMinion": {
    "apiName": "TFT17_IvernMinion",
    "ability": "Meep Impact",
    "expression": "Damage + Damage * PercentEffects",
    "scaling": "AP",
    "perCastBase": [
      300,
      240,
      360,
      540,
      900,
      675,
      675
    ],
    "rationale": "The slam deals Damage magic damage scaling with AP, plus meepwaves that deal an additional PercentEffects fraction of that damage to the row.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Jhin": {
    "apiName": "TFT17_Jhin",
    "ability": "Space Opera",
    "expression": "NumHands * NumAttacks * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      0,
      656,
      992,
      10304,
      7104,
      0,
      0
    ],
    "rationale": "NumHands spectral hands each fire over NumAttacks attacks (16 shots) at ADDamage on the target; omits the smaller final-shot amp (conservative).",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Jinx": {
    "apiName": "TFT17_Jinx",
    "ability": "Explosive Attitude",
    "expression": "BaseBullets * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      48,
      464,
      704,
      1120,
      1760,
      48,
      48
    ],
    "rationale": "BaseBullets rockets (base count; grows with AS), each ADDamage to the first target — all land on a lone target.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Kaisa": {
    "apiName": "TFT17_Kaisa",
    "ability": "Bullet Cluster",
    "expression": "BaseNumMissiles * PercentTargetedMissiles * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      0,
      240,
      360,
      576,
      1088,
      0,
      0
    ],
    "rationale": "Of BaseNumMissiles missiles, the PercentTargetedMissiles fraction strike the current target, each ADDamage — the rest scatter to others.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Karma": {
    "apiName": "TFT17_Karma",
    "ability": "Singularity",
    "expression": "Damage + SecondaryDamage",
    "scaling": "AP",
    "perCastBase": [
      0,
      810,
      1215,
      6000,
      7320,
      0,
      0
    ],
    "rationale": "Vs a lone target the full split Damage lands, plus the target-only SecondaryDamage.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Kindred": {
    "apiName": "TFT17_Kindred",
    "ability": "Cosmic Pursuit",
    "expression": "(NumTargets * SpellDamage) + ((ADDamage + APDamage) / MaxMarks)",
    "scaling": "mixed",
    "perCastBase": [
      0,
      266.667,
      408.333,
      3333.333,
      4425,
      0,
      0
    ],
    "rationale": "Active fires arrows at NumTargets targets each dealing SpellDamage (AD-scaled), plus the passive's ADDamage+APDamage burst (AD+AP mixed) that procs once every MaxMarks marks, averaged over that cycle.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Leblanc": {
    "apiName": "TFT17_Leblanc",
    "ability": "Fracture Reality",
    "expression": "NumClones * NumAttacks * CloneDamageMultiplier * BasicAttackDamage + NumClones * BoltDamage",
    "scaling": "AP",
    "perCastBase": [
      0,
      887.5,
      1343.75,
      13125,
      13950,
      0,
      0
    ],
    "rationale": "NumClones clones each land NumAttacks hits at CloneDamageMultiplier×BasicAttackDamage, then fire one BoltDamage bolt — all magic; the clones are extra attackers the auto model never counts.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Leona": {
    "apiName": "TFT17_Leona",
    "ability": "Shield of Daybreak",
    "expression": "Damage",
    "scaling": "none",
    "perCastBase": [
      0,
      100,
      150,
      225,
      385,
      0,
      0
    ],
    "rationale": "Leona's Bash deals a single instance of flat magic Damage per cast with no AP/AD scaling marker on the base damage value.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Lissandra": {
    "apiName": "TFT17_Lissandra",
    "ability": "Dark Matter",
    "expression": "Damage + SecondaryDamage",
    "scaling": "AP",
    "perCastBase": [
      300,
      300,
      450,
      715,
      1215,
      960,
      960
    ],
    "rationale": "Each cast deals Damage magic damage to the first target hit, then the shard explodes dealing SecondaryDamage magic damage to nearby targets.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Lulu": {
    "apiName": "TFT17_Lulu",
    "ability": "It's Raining Stars",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      2,
      150,
      225,
      360,
      495,
      2,
      2
    ],
    "rationale": "Each cast deals a single instance of Damage (AP-scaling) to nearby enemies, with no additional damage components to combine.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Maokai": {
    "apiName": "TFT17_Maokai",
    "ability": "Grasp of Convergence",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      100,
      100,
      150,
      225,
      300,
      0,
      0
    ],
    "rationale": "Grasp of Convergence's active deals a single instance of magic damage equal to the Damage value, scaling with AP, to each enemy hit.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_MasterYi": {
    "apiName": "TFT17_MasterYi",
    "ability": "Psi Strikes",
    "expression": "2 * Duration * DamageAD",
    "scaling": "AD",
    "perCastBase": [
      600,
      550,
      850,
      6000,
      7200,
      4500,
      4500
    ],
    "rationale": "Active Psi-State fires a DamageAD projection twice a second over Duration(5)s — the total spread across the channel.",
    "source": "claude",
    "dotDuration": 5,
    "model": "claude-opus-4.7"
  },
  "TFT17_Milio": {
    "apiName": "TFT17_Milio",
    "ability": "Mega Time Kick",
    "expression": "Damage + 2*BounceDamage",
    "scaling": "AP",
    "perCastBase": [
      360,
      425,
      640,
      955,
      1625,
      1560,
      1360
    ],
    "rationale": "Initial kick deals Damage, then bounces at 100% chance with odds halving each subsequent bounce (100%+50%+25%+...=2 expected bounces), each dealing BounceDamage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_MissFortune": {
    "apiName": "TFT17_MissFortune",
    "ability": "Gun Goddess Arsenal",
    "expression": "(Tier1Damage + Tier2Damage + Tier3Damage + Tier4Damage + Tier5Damage) / 5",
    "scaling": "none",
    "perCastBase": [
      1.56,
      3.66,
      3.66,
      15.36,
      1.56,
      1.56,
      1.56
    ],
    "rationale": "The ability cycles through five escalating damage tiers per cast across her Conduit/Challenger/Replicator arsenal, so average damage per cast is the sum of the five tier damages divided by 5; no AP/AD scale marker is present, indicating flat damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Mordekaiser": {
    "apiName": "TFT17_Mordekaiser",
    "ability": "Indestructible",
    "expression": "DamagePerProc * Duration",
    "scaling": "AP",
    "perCastBase": [
      0,
      180,
      280,
      400,
      680,
      0,
      0
    ],
    "rationale": "Channel: DamagePerProc magic to adjacent enemies each second over Duration(4)s — the total spread across the shield duration.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Morgana": {
    "apiName": "TFT17_Morgana",
    "ability": "Dark Form",
    "expression": "APDamage * NumEnemies",
    "scaling": "AP",
    "perCastBase": [
      0,
      300,
      450,
      9000,
      0,
      0,
      0
    ],
    "rationale": "Over the transform duration Morgana deals APDamage magic damage to each of NumEnemies closest enemies, scaling with AP.",
    "source": "claude",
    "dotDuration": 3,
    "model": "claude-cli"
  },
  "TFT17_Nami": {
    "apiName": "TFT17_Nami",
    "ability": "Bubble Pop",
    "expression": "Damage + NumProjectiles * FirstBounceDamage",
    "scaling": "AP",
    "perCastBase": [
      620,
      835,
      1245,
      8000,
      9600,
      7600,
      7600
    ],
    "rationale": "The initial bubble damage and each of the NumProjectiles globs both scale with AP, so total average damage per cast sums the burst damage and all glob hits.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Nasus": {
    "apiName": "TFT17_Nasus",
    "ability": "Groovin' Susan",
    "expression": "DamageAP * Duration",
    "scaling": "AP",
    "perCastBase": [
      108,
      180,
      270,
      420,
      720,
      288,
      288
    ],
    "rationale": "Transform aura: DamageAP magic to adjacent enemies each second over Duration(6)s — the total spread across the transform (the %max-HP part is unmodeled).",
    "source": "claude",
    "dotDuration": 6,
    "model": "claude-opus-4.7"
  },
  "TFT17_Nunu": {
    "apiName": "TFT17_Nunu",
    "ability": "Calamity",
    "expression": "InitialDamage + FollowupDamage",
    "scaling": "AP",
    "perCastBase": [
      0,
      220,
      330,
      4000,
      7000,
      0,
      0
    ],
    "rationale": "Each cast deals one instance of InitialDamage on impact plus one instance of FollowupDamage as the astrolabe is pushed, both scaling with AP.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Ornn": {
    "apiName": "TFT17_Ornn",
    "ability": "Disco Inferno",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      200,
      180,
      270,
      430,
      590,
      600,
      600
    ],
    "rationale": "Each cast breathes fire once for a single instance of magic damage equal to Damage, scaling with AP.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Pantheon": {
    "apiName": "TFT17_Pantheon",
    "ability": "Advanced Defences",
    "expression": "TrueDamagePerSecond * Duration",
    "scaling": "AD",
    "perCastBase": [
      0,
      120,
      180,
      280,
      480,
      0,
      0
    ],
    "rationale": "Cone deals the per-second value (physical, AD) each second over Duration(4)s; the heuristic excludes any \"PerSecond\" variable and reads zero ability damage.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Pyke": {
    "apiName": "TFT17_Pyke",
    "ability": "Marked for Death",
    "expression": "SpearDamage + TargetDamage",
    "scaling": "AD",
    "perCastBase": [
      60,
      270,
      405,
      855,
      1405,
      180,
      180
    ],
    "rationale": "The lone target eats the harpoon SpearDamage and the on-target cleave TargetDamage; the dominant TargetDamage is %i:scaleAD%, so scale the burst as AD.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Rammus": {
    "apiName": "TFT17_Rammus",
    "ability": "Gravitational Spin",
    "expression": "DamageAP + DamageArmor",
    "scaling": "mixed",
    "perCastBase": [
      103,
      50.5,
      75.75,
      711,
      612,
      812,
      812
    ],
    "rationale": "Gravitational Spin deals a single magic damage line strike per cast whose base value is the sum of its AP-scaling and Armor-scaling components (DamageAP and DamageArmor), with the shield (ShieldAP) excluded as non-damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_RekSai": {
    "apiName": "TFT17_RekSai",
    "ability": "Upheaval",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      0,
      80,
      120,
      180,
      315,
      0,
      0
    ],
    "rationale": "Each cast deals a single burst of magic damage equal to Damage, scaling with AP as marked by %i:scaleAP% next to @ModifiedDamage@.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Rhaast": {
    "apiName": "TFT17_Rhaast",
    "ability": "Divine Scythe",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      0.2,
      120,
      180,
      300,
      510,
      0.2,
      0.2
    ],
    "rationale": "Rhaast deals one instance of Damage (AD-scaled) per cast when he slashes forward after the durability window; the heal amount is excluded as non-damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Riven": {
    "apiName": "TFT17_Riven",
    "ability": "Time Warp",
    "expression": "Damage + WaveDamage / 3",
    "scaling": "mixed",
    "perCastBase": [
      280,
      143.333,
      215,
      1666.667,
      1700,
      0,
      0
    ],
    "rationale": "Every cast slashes adjacent enemies for Damage, and every third cast additionally deals WaveDamage, averaged over the 3-cast cycle; both damage components adapt to whichever of AD/AP is higher.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Samira": {
    "apiName": "TFT17_Samira",
    "ability": "Jump and Jive",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      260,
      375,
      560,
      900,
      1555,
      810,
      810
    ],
    "rationale": "The active's on-target Damage is physical %i:scaleAD%; the heuristic mis-reads the neutral name as AP. Same number, correct AD scaling.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Shen": {
    "apiName": "TFT17_Shen",
    "ability": "Reality Tear",
    "expression": "BonusDamageOnAttack",
    "scaling": "AP",
    "perCastBase": [
      50,
      25,
      40,
      777,
      777,
      777,
      777
    ],
    "rationale": "Each active cast opens a rift dealing the Passive's stacking bonus damage (which scales with AP) to enemies within it.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Sona": {
    "apiName": "TFT17_Sona",
    "ability": "Psionic Crush",
    "expression": "(4 * DebrisDamage + DebrisRipDamage + SlamDamage) / NumCasts",
    "scaling": "AP",
    "perCastBase": [
      272.5,
      408,
      616,
      2998.8,
      3199,
      2.1,
      2.1
    ],
    "rationale": "Rip+slam every 5th cast (DebrisRipDamage+SlamDamage); the other 4 deal DebrisDamage — averaged over NumCasts.",
    "source": "manual"
  },
  "TFT17_TahmKench": {
    "apiName": "TFT17_TahmKench",
    "ability": "Tounge Lash",
    "expression": "DamageAP + DamageHP",
    "scaling": "AP",
    "perCastBase": [
      120.02,
      45.02,
      60.02,
      1500.02,
      1500.02,
      870.02,
      870.02
    ],
    "rationale": "The active deals ModifiedDamage magic damage composed of an AP-scaling component (DamageAP) plus a max-health-scaling component (DamageHP), summed for one cast.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Talon": {
    "apiName": "TFT17_Talon",
    "ability": "Diviner's Judgment",
    "expression": "ADBleedDamage",
    "scaling": "AD",
    "perCastBase": [
      2.5,
      400,
      600,
      1100,
      1850,
      2.5,
      2.5
    ],
    "rationale": "Stab applies a bleed for ADBleedDamage physical over BleedDuration(18)s — damage over time, not a burst.",
    "source": "claude",
    "dotDuration": 18,
    "model": "claude-opus-4.7"
  },
  "TFT17_Teemo": {
    "apiName": "TFT17_Teemo",
    "ability": "Double Time",
    "expression": "HitDamage + MagicDamage",
    "scaling": "AP",
    "perCastBase": [
      160,
      100,
      150,
      290,
      495,
      275,
      275
    ],
    "rationale": "Each attack deals immediate HitDamage bonus magic damage plus MagicDamage as stacking damage applied over the 6-second PoisonDuration, both scaling with AP.",
    "source": "claude",
    "dotDuration": 6,
    "model": "claude-cli"
  },
  "TFT17_TwistedFate": {
    "apiName": "TFT17_TwistedFate",
    "ability": "Fate's Gambit",
    "expression": "(DamageMin + DamageMax) / 2",
    "scaling": "AP",
    "perCastBase": [
      255,
      307.5,
      457.5,
      690,
      1182.5,
      750,
      750
    ],
    "rationale": "The card value is uniform between 1 and 9, so expected damage is the midpoint of DamageMin and DamageMax — not the max the heuristic reads.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Urgot": {
    "apiName": "TFT17_Urgot",
    "ability": "Unstoppable Dreadnought",
    "expression": "ShotgunDamage",
    "scaling": "AD",
    "perCastBase": [
      90,
      85,
      125,
      200,
      275,
      1.8,
      1.8
    ],
    "rationale": "Each Proximity Blast deals ShotgunDamage physical damage, which scales with AD; the Active itself grants only a shield and resets cooldowns rather than dealing direct damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Veigar": {
    "apiName": "TFT17_Veigar",
    "ability": "Meepteor Shower",
    "expression": "Damage + MiniMeepsPerAstro * MiniDamage",
    "scaling": "AP",
    "perCastBase": [
      330,
      392,
      589,
      890,
      1460,
      1065,
      1065
    ],
    "rationale": "Each cast deals main Meepteor damage plus MiniMeepsPerAstro additional mini Meepteors that each deal MiniDamage, both marked as AP-scaling.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Vex": {
    "apiName": "TFT17_Vex",
    "ability": "Lend Me a Hand, Shadow!",
    "expression": "NumActiveStrikes * ShadowHandMagicDamage",
    "scaling": "AP",
    "perCastBase": [
      600,
      390,
      585,
      3000,
      29997,
      600,
      600
    ],
    "rationale": "On cast, Shadow launches NumActiveStrikes empowered strikes each dealing ShadowHandMagicDamage AP-scaled magic damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Viktor": {
    "apiName": "TFT17_Viktor",
    "ability": "Psionic Storm",
    "expression": "Damage * Duration",
    "scaling": "AP",
    "perCastBase": [
      800,
      800,
      1200,
      2120,
      3400,
      2020,
      2020
    ],
    "rationale": "Channel: Damage magic damage each second over Duration(4)s — the total spread across the storm.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Xayah": {
    "apiName": "TFT17_Xayah",
    "ability": "Stellar Ricochet",
    "expression": "(NumAttacks * ADDamage) + (NumAttacks / RecallFeatherTargets) * PrimaryTargetBonusDamage * (1 - ActivePercentReducedDamage)",
    "scaling": "AD",
    "perCastBase": [
      256,
      310,
      472,
      5720,
      2266,
      1816,
      1816
    ],
    "rationale": "Each of the NumAttacks feathers recalled deals ADDamage physical damage to one of the RecallFeatherTargets closest enemies, while the current (primary) target additionally takes PrimaryTargetBonusDamage per feather it receives, reduced by ActivePercentReducedDamage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Zoe": {
    "apiName": "TFT17_Zoe",
    "ability": "Paddle Star",
    "expression": "(Damage + SecondaryDamage) * (NumRedirects + 1)",
    "scaling": "AP",
    "perCastBase": [
      350,
      520,
      780,
      1340,
      2250,
      1575,
      1075
    ],
    "rationale": "Each cast deals Damage to the first target plus SecondaryDamage to others passed through, and this combined instance repeats NumRedirects additional times as the missile redirects, giving (NumRedirects+1) total damage instances per cast.",
    "source": "claude",
    "model": "claude-cli"
  }
};

/** When this module was last regenerated. */
export const ABILITY_FORMULAS_UPDATED_AT = "2026-07-27T14:36:49.922Z";
/** Provenance string. */
export const ABILITY_FORMULAS_SOURCE = "manual+authored:claude-opus-4.7+claude-cli";

export const ALL_FORMULAS: AbilityFormula[] = Object.values(ABILITY_FORMULAS);

/** Pinned per-cast formula for a unit's ability by apiName, if one exists. */
export function abilityFormula(apiName: string): AbilityFormula | undefined {
  return ABILITY_FORMULAS[apiName];
}
