import type { AbilityFormula } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN ABILITY FORMULAS  —  DO NOT HAND-EDIT
//
// Stage 3 of the theorycraft engine. Each entry pins an exact per-cast BASE
// damage for a unit's ability — the structural combination of its raw cdragon
// variables (multi-cast cycles averaged, per-hit × hit count, DoT totals) that
// the name-only heuristic in combat-model can't infer from variable names.
//
//   `expression`   the human/Claude-supplied STRUCTURE (arithmetic over the
//                  ability's variable names).
//   `perCastBase`  that expression evaluated per star OFFLINE. The runtime
//                  reads ONLY these numbers — it never parses the string.
//
// Regenerated by:
//   • npm run build:formulas                            (manual + authored seed — no key)
//   • CLAUDE_CODE_OAUTH_TOKEN=… npm run build:formulas  (CI: Claude fills rest — subscription, free)
//   • ANTHROPIC_API_KEY=… npm run build:formulas        (CI: Claude fills rest — metered API)
//
// perCastBase is in the SAME native units as the variables, BEFORE AP/AD
// scaling and item amp — the combat model applies those downstream unchanged.
// Indexed by star: perCastBase[1]=1★, [2]=2★, [3]=3★ (mirrors unit-math).
// ---------------------------------------------------------------------------

export const ABILITY_FORMULAS: Record<string, AbilityFormula> = {
  "TFT17_Aatrox": {
    "apiName": "TFT17_Aatrox",
    "ability": "Stellar Slash",
    "expression": "DamageAD + DamagePercentArmor",
    "scaling": "AD",
    "perCastBase": [
      201,
      81.8,
      122.7,
      184.05,
      306.9,
      603,
      603
    ],
    "rationale": "Single cast deals physical damage scaling with AD plus a percent-of-armor component, per the @ModifiedDamage@ (scaleAD scaleArmor) tag.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Akali": {
    "apiName": "TFT17_Akali",
    "ability": "Star Strike",
    "expression": "NumShurikens * DamageAD",
    "scaling": "AD",
    "perCastBase": [
      135,
      185,
      280,
      420,
      700,
      360,
      360
    ],
    "rationale": "NumShurikens kunai, each DamageAD to the first target hit — all land on a lone target.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_AurelionSol": {
    "apiName": "TFT17_AurelionSol",
    "ability": "Deathbeam",
    "expression": "DamagePerSecond * Duration",
    "scaling": "AP",
    "perCastBase": [
      750,
      960,
      1440,
      6000,
      6000,
      4950,
      4950
    ],
    "rationale": "Channel: DamagePerSecond magic damage each second over Duration(3)s — the total spread across the beam.",
    "source": "claude",
    "dotDuration": 3,
    "model": "claude-opus-4.7"
  },
  "TFT17_Aurora": {
    "apiName": "TFT17_Aurora",
    "ability": "Hopped-Up Hacks",
    "expression": "Damage + SplitDamage",
    "scaling": "AP",
    "perCastBase": [
      5.5,
      480,
      720,
      1150,
      1990,
      5.5,
      5.5
    ],
    "rationale": "Each cast deals Damage to each enemy hit plus SplitDamage split among them; summed per cast it's Damage + SplitDamage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Bard": {
    "apiName": "TFT17_Bard",
    "ability": "Ultra Friendly Object",
    "expression": "DamagePerSecond * Duration",
    "scaling": "AP",
    "perCastBase": [
      8,
      880,
      1320,
      12000,
      20000,
      8,
      8
    ],
    "rationale": "Saucer hits the target for DamagePerSecond each second over Duration(4)s — the total spread across its lifetime.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Belveth": {
    "apiName": "TFT17_Belveth",
    "ability": "Tidal Slashes",
    "expression": "BaseNumSlashes * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      600,
      240,
      360,
      540,
      924,
      0,
      0
    ],
    "rationale": "BaseNumSlashes slashes (base count; grows with AS), each ADDamage physical to the target — all land on a lone target.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Blitzcrank": {
    "apiName": "TFT17_Blitzcrank",
    "ability": "Party Crasher",
    "expression": "UppercutDamage + ExplosionDamage",
    "scaling": "AP",
    "perCastBase": [
      370,
      325,
      490,
      5999,
      7000,
      5789,
      10000
    ],
    "rationale": "The knocked-up target takes both UppercutDamage and the ExplosionDamage crash; the heuristic keeps only the larger half.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Briar": {
    "apiName": "TFT17_Briar",
    "ability": "Fish Frenzy",
    "expression": "ADDamage + ADDamage * PercentBonusDamage / 2",
    "scaling": "AD",
    "perCastBase": [
      4.125,
      150,
      225,
      356.25,
      606.25,
      4.125,
      4.125
    ],
    "rationale": "Each cast deals ADDamage physical damage, increased by PercentBonusDamage*100% if target is a tank, averaged assuming half of targets are tanks gives ADDamage*(1 + PercentBonusDamage/2).",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Caitlyn": {
    "apiName": "TFT17_Caitlyn",
    "ability": "Aim For The Head",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      145,
      170,
      255,
      510,
      875,
      455,
      455
    ],
    "rationale": "Passive Headshot deals ModifiedHeadshotDamage (Damage) physical damage scaling with AD per proc; per-cast base is just Damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Chogath": {
    "apiName": "TFT17_Chogath",
    "ability": "Accretion",
    "expression": "BonusDamage + PercentMaximumHealthDamage",
    "scaling": "AP",
    "perCastBase": [
      140.08,
      210.08,
      290.08,
      420.08,
      715.08,
      450.08,
      450.08
    ],
    "rationale": "TotalDamage combines flat BonusDamage with PercentMaximumHealthDamage of target's max HP, scaling with AP per the scaleHealth/scaleAP markers.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Corki": {
    "apiName": "TFT17_Corki",
    "ability": "Asteroid Blaster",
    "expression": "BaseMissiles * MissileAD * (1 + ProcChance / 100 * (ProcDamageMult - 1))",
    "scaling": "AD",
    "perCastBase": [
      787.5,
      882,
      1323,
      8820,
      6300,
      787.5,
      787.5
    ],
    "rationale": "BaseMissiles missiles at MissileAD each (all land on a lone target), with the ProcChance mega-missile (ProcDamageMult×) folded in as expected value.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Diana": {
    "apiName": "TFT17_Diana",
    "ability": "Pale Cascade",
    "expression": "BaseDamage",
    "scaling": "AP",
    "perCastBase": [
      50,
      60,
      90,
      145,
      250,
      240,
      330
    ],
    "rationale": "Active summons orbs that deal ModifiedDamage (BaseDamage) magic damage per cast, scaling with AP.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Ezreal": {
    "apiName": "TFT17_Ezreal",
    "ability": "Temporal Shot",
    "expression": "ADDamage + APDamage + DroneDamage/8",
    "scaling": "mixed",
    "perCastBase": [
      0,
      175,
      262.5,
      399.25,
      677.75,
      0,
      0
    ],
    "rationale": "Each cast deals ADDamage+APDamage physical damage, plus a drone dealing DroneDamage every 8 takedowns, averaged as DroneDamage/8 per cast.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Fiora": {
    "apiName": "TFT17_Fiora",
    "ability": "Perfect Bladework",
    "expression": "NumVitals * VitalDamage",
    "scaling": "AD",
    "perCastBase": [
      300,
      222,
      336,
      4662,
      4662,
      4662,
      4662
    ],
    "rationale": "Active strikes all NumVitals vitals, each for VitalDamage true damage (AD); the AP half is only the heal.",
    "source": "manual",
    "trueDamage": true
  },
  "TFT17_Fizz": {
    "apiName": "TFT17_Fizz",
    "ability": "Meep Bait",
    "expression": "DashDamage + (BiteDamageAP + MeepsPerAstro * BiteDamageMeep) / 3",
    "scaling": "AP",
    "perCastBase": [
      136.667,
      206.667,
      311.667,
      498.333,
      838.333,
      603.333,
      603.333
    ],
    "rationale": "Each cast dashes for DashDamage; every third cast adds a Mega Meep dealing BiteDamageAP plus MeepsPerAstro extra meeps each adding BiteDamageMeep, averaged over the 3-cast cycle.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Gnar": {
    "apiName": "TFT17_Gnar",
    "ability": "Slingshot Maneuver",
    "expression": "DamageAD + DamageAP",
    "scaling": "mixed",
    "perCastBase": [
      230,
      245,
      370,
      605,
      935,
      695,
      695
    ],
    "rationale": "The boomerang cast deals @ModifiedDamage@ physical damage scaling with both AD and AP, so per-cast base sums DamageAD and DamageAP (first-hit value; subsequent pierce hits via DamageReductionPerHit depend on enemy count, and the Meep DPS is a separate continuous effect, not part of the cast).",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Gragas": {
    "apiName": "TFT17_Gragas",
    "ability": "Chemical Rage",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      0,
      200,
      300,
      450,
      765,
      0,
      0
    ],
    "rationale": "Single cast deals Damage magic damage to target and adjacent enemies, scaling with AP per the %i:scaleAP% marker.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Graves": {
    "apiName": "TFT17_Graves",
    "ability": "Collateral Damage",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      400,
      390,
      585,
      5555,
      5555,
      5555,
      5555
    ],
    "rationale": "The shell's on-target Damage is physical %i:scaleAD%; the heuristic mis-reads the neutral name as AP. Same number, correct AD scaling.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Gwen": {
    "apiName": "TFT17_Gwen",
    "ability": "Dance n' Dice",
    "expression": "Damage + AreaDamage",
    "scaling": "AP",
    "perCastBase": [
      300,
      220,
      330,
      600,
      1025,
      1260,
      1260
    ],
    "rationale": "One cast snips the target for Damage and hits cone enemies for AreaDamage; the ResetDamage second snip is conditional on a kill.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Illaoi": {
    "apiName": "TFT17_Illaoi",
    "ability": "Test of Spirit",
    "expression": "HealthDrain * NumEnemies + Damage",
    "scaling": "AP",
    "perCastBase": [
      200,
      245,
      375,
      570,
      765,
      960,
      960
    ],
    "rationale": "Drains HealthDrain true damage from NumEnemies enemies over the duration, then slams for Damage magic damage to nearby enemies.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_IvernMinion": {
    "apiName": "TFT17_IvernMinion",
    "ability": "Meep Impact",
    "expression": "Damage * (1 + PercentEffects)",
    "scaling": "AP",
    "perCastBase": [
      300,
      240,
      360,
      540,
      900,
      675,
      675
    ],
    "rationale": "Cast deals Damage to the primary target via slam, and the meepwave deals PercentEffects of that damage to others in the target's row.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Jhin": {
    "apiName": "TFT17_Jhin",
    "ability": "Space Opera",
    "expression": "NumHands * NumAttacks * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      0,
      656,
      992,
      10304,
      7104,
      0,
      0
    ],
    "rationale": "NumHands spectral hands each fire over NumAttacks attacks (16 shots) at ADDamage on the target; omits the smaller final-shot amp (conservative).",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Jinx": {
    "apiName": "TFT17_Jinx",
    "ability": "Explosive Attitude",
    "expression": "BaseBullets * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      48,
      464,
      704,
      1120,
      1760,
      48,
      48
    ],
    "rationale": "BaseBullets rockets (base count; grows with AS), each ADDamage to the first target — all land on a lone target.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Kaisa": {
    "apiName": "TFT17_Kaisa",
    "ability": "Bullet Cluster",
    "expression": "BaseNumMissiles * PercentTargetedMissiles * ADDamage",
    "scaling": "AD",
    "perCastBase": [
      0,
      240,
      360,
      576,
      1088,
      0,
      0
    ],
    "rationale": "Of BaseNumMissiles missiles, the PercentTargetedMissiles fraction strike the current target, each ADDamage — the rest scatter to others.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Karma": {
    "apiName": "TFT17_Karma",
    "ability": "Singularity",
    "expression": "Damage + SecondaryDamage",
    "scaling": "AP",
    "perCastBase": [
      0,
      750,
      1125,
      6000,
      7320,
      0,
      0
    ],
    "rationale": "Vs a lone target the full split Damage lands, plus the target-only SecondaryDamage.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Kindred": {
    "apiName": "TFT17_Kindred",
    "ability": "Cosmic Pursuit",
    "expression": "NumTargets * ADDamage + (SpellDamage + ADDamage + APDamage) / MaxMarks",
    "scaling": "mixed",
    "perCastBase": [
      0,
      411.667,
      626.667,
      5033.333,
      5895,
      0,
      0
    ],
    "rationale": "Active fires NumTargets arrows each dealing ADDamage (AD-scaling); each cast adds 1 mark, so on average every MaxMarks casts the passive procs once dealing the combined SpellDamage + AD + AP components.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Leblanc": {
    "apiName": "TFT17_Leblanc",
    "ability": "Fracture Reality",
    "expression": "NumClones * NumAttacks * CloneDamageMultiplier * BasicAttackDamage + NumClones * BoltDamage",
    "scaling": "AP",
    "perCastBase": [
      0,
      787.5,
      1181.25,
      13125,
      13950,
      0,
      0
    ],
    "rationale": "NumClones clones each land NumAttacks hits at CloneDamageMultiplier×BasicAttackDamage, then fire one BoltDamage bolt — all magic; the clones are extra attackers the auto model never counts.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Leona": {
    "apiName": "TFT17_Leona",
    "ability": "Shield of Daybreak",
    "expression": "Damage",
    "scaling": "none",
    "perCastBase": [
      0,
      100,
      150,
      225,
      385,
      0,
      0
    ],
    "rationale": "A single cast bashes the current target once for the Damage value as magic damage; the %i:scaleArmor%%i:scaleMR% markers indicate defensive scaling on the caster, not AP/AD damage scaling.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Lissandra": {
    "apiName": "TFT17_Lissandra",
    "ability": "Dark Matter",
    "expression": "Damage + SecondaryDamage",
    "scaling": "AP",
    "perCastBase": [
      300,
      300,
      450,
      715,
      1215,
      960,
      960
    ],
    "rationale": "One cast deals initial magic damage to the first target hit plus secondary explosion damage, both scaling with AP.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Lulu": {
    "apiName": "TFT17_Lulu",
    "ability": "It's Raining Stars",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      2,
      150,
      225,
      360,
      495,
      2,
      2
    ],
    "rationale": "One cast deals Damage magic damage to NumEnemies nearby enemies; per-cast damage to one target is just Damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Maokai": {
    "apiName": "TFT17_Maokai",
    "ability": "Grasp of Convergence",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      100,
      100,
      150,
      225,
      300,
      0,
      0
    ],
    "rationale": "Active deals DamageTotal magic damage (scaling AP) to each enemy hit in the X-shape, with no multi-hit or cycle modifier on the base damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_MasterYi": {
    "apiName": "TFT17_MasterYi",
    "ability": "Psi Strikes",
    "expression": "2 * Duration * DamageAD",
    "scaling": "AD",
    "perCastBase": [
      600,
      500,
      750,
      6000,
      7200,
      4500,
      4500
    ],
    "rationale": "Active Psi-State fires a DamageAD projection twice a second over Duration(5)s — the total spread across the channel.",
    "source": "claude",
    "dotDuration": 5,
    "model": "claude-opus-4.7"
  },
  "TFT17_Milio": {
    "apiName": "TFT17_Milio",
    "ability": "Mega Time Kick",
    "expression": "Damage + 2 * BounceDamage",
    "scaling": "AP",
    "perCastBase": [
      360,
      425,
      640,
      955,
      1625,
      1560,
      1360
    ],
    "rationale": "Initial kick deals Damage, then a 100% bounce plus halving-probability subsequent bounces form a geometric series summing to 2 expected bounces of BounceDamage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Mordekaiser": {
    "apiName": "TFT17_Mordekaiser",
    "ability": "Indestructible",
    "expression": "DamagePerProc * Duration",
    "scaling": "AP",
    "perCastBase": [
      0,
      180,
      280,
      400,
      680,
      0,
      0
    ],
    "rationale": "Channel: DamagePerProc magic to adjacent enemies each second over Duration(4)s — the total spread across the shield duration.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Morgana": {
    "apiName": "TFT17_Morgana",
    "ability": "Dark Form",
    "expression": "APDamage * NumEnemies",
    "scaling": "AP",
    "perCastBase": [
      0,
      300,
      450,
      9000,
      0,
      0,
      0
    ],
    "rationale": "Over the 3-second duration, deals APDamage magic damage to the closest NumEnemies enemies.",
    "source": "claude",
    "dotDuration": 3,
    "model": "claude-cli"
  },
  "TFT17_Nami": {
    "apiName": "TFT17_Nami",
    "ability": "Bubble Pop",
    "expression": "Damage + NumProjectiles * FirstBounceDamage",
    "scaling": "AP",
    "perCastBase": [
      620,
      770,
      1155,
      8000,
      9600,
      7600,
      7600
    ],
    "rationale": "One cast deals the main bubble Damage plus NumProjectiles globs each dealing FirstBounceDamage, both marked with scaleAP.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Nasus": {
    "apiName": "TFT17_Nasus",
    "ability": "Groovin' Susan",
    "expression": "DamageAP * Duration",
    "scaling": "AP",
    "perCastBase": [
      108,
      180,
      270,
      420,
      720,
      288,
      288
    ],
    "rationale": "Transform aura: DamageAP magic to adjacent enemies each second over Duration(6)s — the total spread across the transform (the %max-HP part is unmodeled).",
    "source": "claude",
    "dotDuration": 6,
    "model": "claude-opus-4.7"
  },
  "TFT17_Nunu": {
    "apiName": "TFT17_Nunu",
    "ability": "Calamity",
    "expression": "InitialDamage + FollowupDamage",
    "scaling": "AP",
    "perCastBase": [
      0,
      220,
      330,
      4000,
      7000,
      0,
      0
    ],
    "rationale": "One cast deals InitialDamage in a 2-hex area then FollowupDamage as the astrolabe pushes across the board; both are magic damage scaling with AP.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Ornn": {
    "apiName": "TFT17_Ornn",
    "ability": "Disco Inferno",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      200,
      180,
      270,
      430,
      590,
      600,
      600
    ],
    "rationale": "Active deals Damage magic damage in a cone once per cast, scaling with AP per the %i:scaleAP% marker next to ModifiedDamage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Pantheon": {
    "apiName": "TFT17_Pantheon",
    "ability": "Advanced Defences",
    "expression": "TrueDamagePerSecond * Duration",
    "scaling": "AD",
    "perCastBase": [
      0,
      120,
      180,
      280,
      480,
      0,
      0
    ],
    "rationale": "Cone deals the per-second value (physical, AD) each second over Duration(4)s; the heuristic excludes any \"PerSecond\" variable and reads zero ability damage.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Pyke": {
    "apiName": "TFT17_Pyke",
    "ability": "Marked for Death",
    "expression": "SpearDamage + TargetDamage",
    "scaling": "AD",
    "perCastBase": [
      60,
      270,
      405,
      855,
      1405,
      180,
      180
    ],
    "rationale": "The lone target eats the harpoon SpearDamage and the on-target cleave TargetDamage; the dominant TargetDamage is %i:scaleAD%, so scale the burst as AD.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Rammus": {
    "apiName": "TFT17_Rammus",
    "ability": "Gravitational Spin",
    "expression": "DamageAP + DamageArmor",
    "scaling": "AP",
    "perCastBase": [
      103,
      50.5,
      75.75,
      711,
      612,
      812,
      812
    ],
    "rationale": "Single cast strikes enemies in a three hex line dealing ModifiedDamage scaling with AP and Armor; passive damage requires being attacked and is excluded as it isn't part of the cast.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_RekSai": {
    "apiName": "TFT17_RekSai",
    "ability": "Upheaval",
    "expression": "Damage",
    "scaling": "AP",
    "perCastBase": [
      0,
      80,
      120,
      180,
      315,
      0,
      0
    ],
    "rationale": "Single knock-up cast deals ModifiedDamage which scales with AP, represented by the Damage variable per star.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Rhaast": {
    "apiName": "TFT17_Rhaast",
    "ability": "Divine Scythe",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      0.2,
      120,
      180,
      300,
      510,
      0.2,
      0.2
    ],
    "rationale": "Single cast slashes forward dealing Damage physical damage to enemies hit, scaling with AD per the %i:scaleAD% marker.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Riven": {
    "apiName": "TFT17_Riven",
    "ability": "Time Warp",
    "expression": "(2*Damage + (Damage + WaveDamage)) / 3",
    "scaling": "mixed",
    "perCastBase": [
      280,
      143.333,
      215,
      1666.667,
      1700,
      0,
      0
    ],
    "rationale": "Active slashes for Damage each cast; every third cast additionally launches a wave dealing WaveDamage, averaged over the 3-cast cycle, and the ability adapts to AD or AP whichever is higher.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Samira": {
    "apiName": "TFT17_Samira",
    "ability": "Jump and Jive",
    "expression": "Damage",
    "scaling": "AD",
    "perCastBase": [
      260,
      375,
      560,
      900,
      1555,
      810,
      810
    ],
    "rationale": "The active's on-target Damage is physical %i:scaleAD%; the heuristic mis-reads the neutral name as AP. Same number, correct AD scaling.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Shen": {
    "apiName": "TFT17_Shen",
    "ability": "Reality Tear",
    "expression": "BonusDamageOnAttack",
    "scaling": "AP",
    "perCastBase": [
      50,
      25,
      40,
      777,
      777,
      777,
      777
    ],
    "rationale": "Active opens a rift dealing the Passive's flat bonus magic damage (BonusDamageOnAttack) once to all enemies inside, which becomes true damage from the third cast onward.",
    "source": "claude",
    "trueDamage": true,
    "model": "claude-cli"
  },
  "TFT17_Sona": {
    "apiName": "TFT17_Sona",
    "ability": "Psionic Crush",
    "expression": "(4 * DebrisDamage + DebrisRipDamage + SlamDamage) / NumCasts",
    "scaling": "AP",
    "perCastBase": [
      272.5,
      408,
      616,
      2998.8,
      3199,
      2.1,
      2.1
    ],
    "rationale": "Rip+slam every 5th cast (DebrisRipDamage+SlamDamage); the other 4 deal DebrisDamage — averaged over NumCasts.",
    "source": "manual"
  },
  "TFT17_TahmKench": {
    "apiName": "TFT17_TahmKench",
    "ability": "Tounge Lash",
    "expression": "DamageAP + DamageHP",
    "scaling": "AP",
    "perCastBase": [
      120.02,
      45.02,
      60.02,
      1500.02,
      1500.02,
      870.02,
      870.02
    ],
    "rationale": "Active deals ModifiedDamage to all enemies within two hexes, scaling with AP (DamageAP) and the caster's max Health (DamageHP).",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Talon": {
    "apiName": "TFT17_Talon",
    "ability": "Diviner's Judgment",
    "expression": "ADBleedDamage",
    "scaling": "AD",
    "perCastBase": [
      2.5,
      400,
      600,
      1000,
      1700,
      2.5,
      2.5
    ],
    "rationale": "Stab applies a bleed for ADBleedDamage physical over BleedDuration(18)s — damage over time, not a burst.",
    "source": "claude",
    "dotDuration": 18,
    "model": "claude-opus-4.7"
  },
  "TFT17_Teemo": {
    "apiName": "TFT17_Teemo",
    "ability": "Double Time",
    "expression": "HitDamage + MagicDamage",
    "scaling": "AP",
    "perCastBase": [
      160,
      95,
      140,
      270,
      470,
      275,
      275
    ],
    "rationale": "Passive attacks deal HitDamage bonus magic damage plus MagicDamage stacking magic damage over PoisonDuration (6) seconds.",
    "source": "claude",
    "dotDuration": 6,
    "model": "claude-cli"
  },
  "TFT17_TwistedFate": {
    "apiName": "TFT17_TwistedFate",
    "ability": "Fate's Gambit",
    "expression": "(DamageMin + DamageMax) / 2",
    "scaling": "AP",
    "perCastBase": [
      255,
      285,
      427.5,
      645,
      1095,
      750,
      750
    ],
    "rationale": "The card value is uniform between 1 and 9, so expected damage is the midpoint of DamageMin and DamageMax — not the max the heuristic reads.",
    "source": "claude",
    "model": "claude-opus-4.7"
  },
  "TFT17_Urgot": {
    "apiName": "TFT17_Urgot",
    "ability": "Unstoppable Dreadnought",
    "expression": "ShotgunDamage",
    "scaling": "AD",
    "perCastBase": [
      90,
      85,
      125,
      200,
      275,
      1.8,
      1.8
    ],
    "rationale": "Each cast resets Proximity Blast cooldowns and fires a single cone blast dealing ShotgunDamage physical (AD-scaling) damage; falloff and multi-hex hits are positional variance not averaged here.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Veigar": {
    "apiName": "TFT17_Veigar",
    "ability": "Meepteor Shower",
    "expression": "Damage + MiniMeepsPerAstro * MiniDamage",
    "scaling": "AP",
    "perCastBase": [
      330,
      372,
      559,
      840,
      1450,
      1065,
      1065
    ],
    "rationale": "Main Meepteor deals Damage; Meep bonus adds MiniMeepsPerAstro mini meteors each dealing MiniDamage magic damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Vex": {
    "apiName": "TFT17_Vex",
    "ability": "Lend Me a Hand, Shadow!",
    "expression": "ShadowHandMagicDamage * NumActiveStrikes",
    "scaling": "AP",
    "perCastBase": [
      600,
      390,
      585,
      3000,
      29997,
      600,
      600
    ],
    "rationale": "Active cast launches NumActiveStrikes empowered strikes each dealing ShadowHandMagicDamage magic damage.",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Viktor": {
    "apiName": "TFT17_Viktor",
    "ability": "Psionic Storm",
    "expression": "Damage * Duration",
    "scaling": "AP",
    "perCastBase": [
      800,
      760,
      1160,
      2000,
      3400,
      2020,
      2020
    ],
    "rationale": "Channel: Damage magic damage each second over Duration(4)s — the total spread across the storm.",
    "source": "claude",
    "dotDuration": 4,
    "model": "claude-opus-4.7"
  },
  "TFT17_Xayah": {
    "apiName": "TFT17_Xayah",
    "ability": "Stellar Ricochet",
    "expression": "RecallFeatherTargets*ADDamage + PrimaryTargetBonusDamage*AttackNumEnemies*NumAttacks",
    "scaling": "AD",
    "perCastBase": [
      300,
      585,
      924,
      8700,
      1425,
      1200,
      1200
    ],
    "rationale": "Each of 3 recalled feathers deals ADDamage to closest enemies, plus primary target takes PrimaryTargetBonusDamage per feather (AttackNumEnemies bounces × NumAttacks attacks = total feathers generated).",
    "source": "claude",
    "model": "claude-cli"
  },
  "TFT17_Zoe": {
    "apiName": "TFT17_Zoe",
    "ability": "Paddle Star",
    "expression": "Damage + NumRedirects*Damage",
    "scaling": "AP",
    "perCastBase": [
      250,
      340,
      510,
      900,
      1500,
      1050,
      775
    ],
    "rationale": "Initial hit deals Damage to first target, then redirects NumRedirects times each repeating the damage to the first target hit.",
    "source": "claude",
    "model": "claude-cli"
  }
};

/** When this module was last regenerated. */
export const ABILITY_FORMULAS_UPDATED_AT = "2026-06-03T18:50:00.464Z";
/** Provenance string. */
export const ABILITY_FORMULAS_SOURCE = "manual+authored:claude-opus-4.7+claude-cli";

export const ALL_FORMULAS: AbilityFormula[] = Object.values(ABILITY_FORMULAS);

/** Pinned per-cast formula for a unit's ability by apiName, if one exists. */
export function abilityFormula(apiName: string): AbilityFormula | undefined {
  return ABILITY_FORMULAS[apiName];
}
