import type { AugmentStat } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN AUGMENT OVERLAY  —  DO NOT HAND-EDIT
//
// Regenerated by the data pipeline (any manual change here is overwritten):
//   • npm run refresh  — crawls the Riot API, tallies which augments each comp
//                        actually ran and how they placed (needs RIOT_API_KEY)
//
// Keyed by comp id. Each comp maps to its top augments by real pick rate, with
// the placement they produced. A missing key (or empty array) means "no crawled
// augment data yet" — the guide then falls back to the archetype priorities in
// comps.ts rather than inventing numbers.
// ---------------------------------------------------------------------------

export const COMP_AUGMENT_STATS: Record<string, AugmentStat[]> = {};

/** When the augment overlay was last regenerated (empty until the first crawl). */
export const AUGMENT_STATS_UPDATED_AT = '';
/** Provenance string for the overlay (empty until the first crawl). */
export const AUGMENT_STATS_SOURCE = '';

/** Real crawled augments for a comp, best (lowest avg place) first; [] when none yet. */
export function augmentsForComp(compId: string): AugmentStat[] {
  return COMP_AUGMENT_STATS[compId] ?? [];
}
