// AUTO-GENERATED by scripts/build-champions.ts — DO NOT EDIT BY HAND.
// Source: CommunityDragon TFT (TFTSet17). Regenerate with: npm run champions
import type { Champion } from '../types';

export const CHAMPIONS_SET = 'Set 17';
export const CHAMPIONS_UPDATED_AT = "2026-05-31T13:33:04.601Z";

export const CHAMPIONS: Champion[] = [
  {
    "id": "aatrox",
    "apiName": "TFT17_Aatrox",
    "name": "Aatrox",
    "cost": 1,
    "traits": [
      "N.O.V.A.",
      "Bastion"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_aatrox/hud/tft17_aatrox_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_aatrox/skins/base/images/tft17_aatrox_splash_tile_30.tft_set17.png"
  },
  {
    "id": "briar",
    "apiName": "TFT17_Briar",
    "name": "Briar",
    "cost": 1,
    "traits": [
      "Anima",
      "Primordian",
      "Rogue"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_briar/hud/tft17_briar_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_briar/skins/base/images/tft17_briar_splash_tile_10.tft_set17.png"
  },
  {
    "id": "caitlyn",
    "apiName": "TFT17_Caitlyn",
    "name": "Caitlyn",
    "cost": 1,
    "traits": [
      "N.O.V.A.",
      "Fateweaver"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_caitlyn/hud/tft17_caitlyn_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_caitlyn/skins/base/images/tft17_caitlyn_splash_tile_48.tft_set17.png"
  },
  {
    "id": "chogath",
    "apiName": "TFT17_Chogath",
    "name": "Cho'Gath",
    "cost": 1,
    "traits": [
      "Dark Star",
      "Brawler"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_chogath/hud/tft17_chogath_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_chogath/skins/base/images/tft17_chogath_splash_tile_7.tft_set17.png"
  },
  {
    "id": "ezreal",
    "apiName": "TFT17_Ezreal",
    "name": "Ezreal",
    "cost": 1,
    "traits": [
      "Timebreaker",
      "Sniper"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_ezreal/hud/tft17_ezreal_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_ezreal/skins/base/images/tft17_ezreal_splash_tile_5.tft_set17.png"
  },
  {
    "id": "leona",
    "apiName": "TFT17_Leona",
    "name": "Leona",
    "cost": 1,
    "traits": [
      "Arbiter",
      "Vanguard"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_leona/hud/tft17_leona_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_leona/skins/base/images/tft17_leona_splash_tile_64.tft_set17.png"
  },
  {
    "id": "lissandra",
    "apiName": "TFT17_Lissandra",
    "name": "Lissandra",
    "cost": 1,
    "traits": [
      "Dark Star",
      "Shepherd",
      "Replicator"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_lissandra/hud/tft17_lissandra_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_lissandra/skins/base/images/tft17_lissandra_splash_tile_12.tft_set17.png"
  },
  {
    "id": "nasus",
    "apiName": "TFT17_Nasus",
    "name": "Nasus",
    "cost": 1,
    "traits": [
      "Space Groove",
      "Vanguard"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_nasus/hud/tft17_nasus_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_nasus/skins/base/images/tft17_nasus_splash_tile_25.tft_set17.png"
  },
  {
    "id": "poppy",
    "apiName": "TFT17_Poppy",
    "name": "Poppy",
    "cost": 1,
    "traits": [
      "Meeple",
      "Bastion"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_poppy/hud/tft17_poppy_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_poppy/skins/base/images/tft17_poppy_splash_tile_16.tft_set17.png"
  },
  {
    "id": "reksai",
    "apiName": "TFT17_RekSai",
    "name": "Rek'Sai",
    "cost": 1,
    "traits": [
      "Primordian",
      "Brawler"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_reksai/hud/tft17_reksai_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_reksai/skins/base/images/tft17_reksai_splash_tile_26.tft_set17.png"
  },
  {
    "id": "talon",
    "apiName": "TFT17_Talon",
    "name": "Talon",
    "cost": 1,
    "traits": [
      "Stargazer",
      "Rogue"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_talon/hud/tft17_talon_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_talon/skins/base/images/tft17_talon_splash_tile_39.tft_set17.png"
  },
  {
    "id": "teemo",
    "apiName": "TFT17_Teemo",
    "name": "Teemo",
    "cost": 1,
    "traits": [
      "Space Groove",
      "Shepherd"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_teemo/hud/tft17_teemo_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_teemo/skins/base/images/tft17_teemo_splash_tile_47.tft_set17.png"
  },
  {
    "id": "twistedfate",
    "apiName": "TFT17_TwistedFate",
    "name": "Twisted Fate",
    "cost": 1,
    "traits": [
      "Stargazer",
      "Fateweaver"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_twistedfate/hud/tft17_twistedfate_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_twistedfate/skins/base/images/tft17_twistedfate_splash_tile_45.tft_set17.png"
  },
  {
    "id": "veigar",
    "apiName": "TFT17_Veigar",
    "name": "Veigar",
    "cost": 1,
    "traits": [
      "Meeple",
      "Replicator"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_veigar/hud/tft17_veigar_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_veigar/skins/base/images/tft17_veigar_splash_tile_32.tft_set17.png"
  },
  {
    "id": "akali",
    "apiName": "TFT17_Akali",
    "name": "Akali",
    "cost": 2,
    "traits": [
      "N.O.V.A.",
      "Marauder"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_akali/hud/tft17_akali_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_akali/skins/base/images/tft17_akali_splash_tile_68.tft_set17.png"
  },
  {
    "id": "belveth",
    "apiName": "TFT17_Belveth",
    "name": "Bel'Veth",
    "cost": 2,
    "traits": [
      "Primordian",
      "Challenger",
      "Marauder"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_belveth/hud/tft17_belveth_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_belveth/skins/base/images/tft17_belveth_splash_tile_19.tft_set17.png"
  },
  {
    "id": "gnar",
    "apiName": "TFT17_Gnar",
    "name": "Gnar",
    "cost": 2,
    "traits": [
      "Meeple",
      "Sniper"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_gnar/hud/tft17_gnar_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_gnar/skins/base/images/tft17_gnar_splash_tile_15.tft_set17.png"
  },
  {
    "id": "gragas",
    "apiName": "TFT17_Gragas",
    "name": "Gragas",
    "cost": 2,
    "traits": [
      "Psionic",
      "Brawler"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_gragas/hud/tft17_gragas_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_gragas/skins/base/images/tft17_gragas_splash_tile_10.tft_set17.png"
  },
  {
    "id": "gwen",
    "apiName": "TFT17_Gwen",
    "name": "Gwen",
    "cost": 2,
    "traits": [
      "Space Groove",
      "Rogue"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_gwen/hud/tft17_gwen_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_gwen/skins/base/images/tft17_gwen_splash_tile_1.tft_set17.png"
  },
  {
    "id": "jax",
    "apiName": "TFT17_Jax",
    "name": "Jax",
    "cost": 2,
    "traits": [
      "Stargazer",
      "Bastion"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_jax/hud/tft17_jax_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_jax/skins/base/images/tft17_jax_mobile.tft_set17.png"
  },
  {
    "id": "jinx",
    "apiName": "TFT17_Jinx",
    "name": "Jinx",
    "cost": 2,
    "traits": [
      "Anima",
      "Challenger"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_jinx/hud/tft17_jinx_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_jinx/skins/base/images/tft17_jinx_splash_tile_38.tft_set17.png"
  },
  {
    "id": "ivernminion",
    "apiName": "TFT17_IvernMinion",
    "name": "Meepsie",
    "cost": 2,
    "traits": [
      "Meeple",
      "Shepherd",
      "Voyager"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_ivernminion/hud/tft17_ivernminion_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_ivernminion/skins/base/images/tft17_ivernminion_splash_tile_27.tft_set17.png"
  },
  {
    "id": "milio",
    "apiName": "TFT17_Milio",
    "name": "Milio",
    "cost": 2,
    "traits": [
      "Timebreaker",
      "Fateweaver"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_milio/hud/tft17_milio_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_milio/skins/base/images/tft17_milio_splash_tile_0.tft_set17.png"
  },
  {
    "id": "mordekaiser",
    "apiName": "TFT17_Mordekaiser",
    "name": "Mordekaiser",
    "cost": 2,
    "traits": [
      "Dark Star",
      "Conduit",
      "Vanguard"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_mordekaiser/hud/tft17_mordekaiser_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_mordekaiser/skins/base/images/tft17_mordekaiser_splash_tile_6.tft_set17.png"
  },
  {
    "id": "pantheon",
    "apiName": "TFT17_Pantheon",
    "name": "Pantheon",
    "cost": 2,
    "traits": [
      "Timebreaker",
      "Brawler",
      "Replicator"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_pantheon/hud/tft17_pantheon_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_pantheon/skins/base/images/tft17_pantheon_splash_tile_16.tft_set17.png"
  },
  {
    "id": "pyke",
    "apiName": "TFT17_Pyke",
    "name": "Pyke",
    "cost": 2,
    "traits": [
      "Psionic",
      "Voyager"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_pyke/hud/tft17_pyke_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_pyke/skins/base/images/tft17_pyke_splash_tile_25.tft_set17.png"
  },
  {
    "id": "zoe",
    "apiName": "TFT17_Zoe",
    "name": "Zoe",
    "cost": 2,
    "traits": [
      "Arbiter",
      "Conduit"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_zoe/hud/tft17_zoe_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_zoe/skins/base/images/tft17_zoe_splash_tile_43.tft_set17.png"
  },
  {
    "id": "aurora",
    "apiName": "TFT17_Aurora",
    "name": "Aurora",
    "cost": 3,
    "traits": [
      "Anima",
      "Voyager"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_aurora/hud/tft17_aurora_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_aurora/skins/base/images/tft17_aurora_splash_tile_1.tft_set17.png"
  },
  {
    "id": "diana",
    "apiName": "TFT17_Diana",
    "name": "Diana",
    "cost": 3,
    "traits": [
      "Arbiter",
      "Challenger"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/ux/tft/championsplashes/patching/tft17_diana_teamplanner_splash.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_diana/skins/base/images/tft17_dianasplash_mobile.tft_set17.png"
  },
  {
    "id": "fizz",
    "apiName": "TFT17_Fizz",
    "name": "Fizz",
    "cost": 3,
    "traits": [
      "Meeple",
      "Rogue"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_fizz/hud/tft17_fizz_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_fizz/skins/base/images/tft17_fizz_splash_tile_26.tft_set17.png"
  },
  {
    "id": "illaoi",
    "apiName": "TFT17_Illaoi",
    "name": "Illaoi",
    "cost": 3,
    "traits": [
      "Anima",
      "Vanguard",
      "Shepherd"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_illaoi/hud/tft17_illaoi_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_illaoi/skins/base/images/tft17_illaoi_splash_tile_27.tft_set17.png"
  },
  {
    "id": "kaisa",
    "apiName": "TFT17_Kaisa",
    "name": "Kai'Sa",
    "cost": 3,
    "traits": [
      "Dark Star",
      "Rogue"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_kaisa/hud/tft17_kaisa_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_kaisa/skins/base/images/tft17_kaisa_splash_tile_69.tft_set17.png"
  },
  {
    "id": "lulu",
    "apiName": "TFT17_Lulu",
    "name": "Lulu",
    "cost": 3,
    "traits": [
      "Stargazer",
      "Replicator"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_lulu/hud/tft17_lulu_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_lulu/skins/base/images/tft17_lulu_splash_tile_14.tft_set17.png"
  },
  {
    "id": "maokai",
    "apiName": "TFT17_Maokai",
    "name": "Maokai",
    "cost": 3,
    "traits": [
      "N.O.V.A.",
      "Brawler"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_maokai/hud/tft17_maokai_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_maokai/skins/base/images/tft17_maokai_splash_tile_33.tft_set17.png"
  },
  {
    "id": "missfortune",
    "apiName": "TFT17_MissFortune",
    "name": "Miss Fortune",
    "cost": 3,
    "traits": [
      "Gun Goddess"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_missfortune/hud/tft17_missfortune_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_missfortune/skins/base/images/tft17_missfortune_splash_tile_16.tft_set17.png"
  },
  {
    "id": "ornn",
    "apiName": "TFT17_Ornn",
    "name": "Ornn",
    "cost": 3,
    "traits": [
      "Space Groove",
      "Bastion"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_ornn/hud/tft17_ornn_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_ornn/skins/base/images/tft17_ornn_splash_tile_11.tft_set17.png"
  },
  {
    "id": "rhaast",
    "apiName": "TFT17_Rhaast",
    "name": "Rhaast",
    "cost": 3,
    "traits": [
      "Redeemer"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_rhaast/hud/tft17_kayn_slay_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_rhaast/skins/base/images/tft17_kaynsplash_tile.tft_set17.png"
  },
  {
    "id": "samira",
    "apiName": "TFT17_Samira",
    "name": "Samira",
    "cost": 3,
    "traits": [
      "Space Groove",
      "Sniper"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_samira/hud/tft17_samira_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_samira/skins/base/images/tft17_samira_splash_tile_10.tft_set17.png"
  },
  {
    "id": "urgot",
    "apiName": "TFT17_Urgot",
    "name": "Urgot",
    "cost": 3,
    "traits": [
      "Mecha",
      "Brawler",
      "Marauder"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_urgot/hud/tft17_urgot_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_urgot/skins/base/images/tft17_urgot_splash_tile_32.tft_set17.png"
  },
  {
    "id": "viktor",
    "apiName": "TFT17_Viktor",
    "name": "Viktor",
    "cost": 3,
    "traits": [
      "Psionic",
      "Conduit"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_viktor/hud/tft17_viktor_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_viktor/skins/base/images/tft17_viktor_splash_tile_5.tft_set17.png"
  },
  {
    "id": "aurelionsol",
    "apiName": "TFT17_AurelionSol",
    "name": "Aurelion Sol",
    "cost": 4,
    "traits": [
      "Mecha",
      "Conduit"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_aurelionsol/hud/tft17_aurelionsol_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_aurelionsol/skins/base/images/tft17_aurelionsol_splash_tile_2.tft_set17.png"
  },
  {
    "id": "corki",
    "apiName": "TFT17_Corki",
    "name": "Corki",
    "cost": 4,
    "traits": [
      "Meeple",
      "Fateweaver"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_corki/hud/tft17_corki_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_corki/skins/base/images/tft17_corki_splash_tile_26.tft_set17.png"
  },
  {
    "id": "karma",
    "apiName": "TFT17_Karma",
    "name": "Karma",
    "cost": 4,
    "traits": [
      "Dark Star",
      "Voyager"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_karma/hud/tft17_karma_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_karma/skins/base/images/tft17_karma_splash_tile_8.tft_set17.png"
  },
  {
    "id": "kindred",
    "apiName": "TFT17_Kindred",
    "name": "Kindred",
    "cost": 4,
    "traits": [
      "N.O.V.A.",
      "Challenger"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_kindred/hud/tft17_kindred_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_kindred/skins/base/images/tft17_kindred_splash_tile_23.tft_set17.png"
  },
  {
    "id": "leblanc",
    "apiName": "TFT17_Leblanc",
    "name": "LeBlanc",
    "cost": 4,
    "traits": [
      "Arbiter",
      "Shepherd"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_leblanc/hud/tft17_leblanc_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_leblanc/skins/base/images/tft17_leblanc_splash_tile_29.tft_set17.png"
  },
  {
    "id": "masteryi",
    "apiName": "TFT17_MasterYi",
    "name": "Master Yi",
    "cost": 4,
    "traits": [
      "Psionic",
      "Marauder"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_masteryi/hud/tft17_masteryi_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_masteryi/skins/base/images/tft17_masteryi_splash_tile_33.tft_set17.png"
  },
  {
    "id": "morgana",
    "apiName": "TFT17_Morgana",
    "name": "Morgana",
    "cost": 4,
    "traits": [
      "Dark Lady"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_morgana/hud/tft17_morgana_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_morgana/skins/base/images/tft17_morgana_splash_tile_50.tft_set17.png"
  },
  {
    "id": "nami",
    "apiName": "TFT17_Nami",
    "name": "Nami",
    "cost": 4,
    "traits": [
      "Space Groove",
      "Replicator"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_nami/hud/tft17_nami_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_nami/skins/base/images/tft17_nami_splash_tile_41.tft_set17.png"
  },
  {
    "id": "nunu",
    "apiName": "TFT17_Nunu",
    "name": "Nunu & Willump",
    "cost": 4,
    "traits": [
      "Stargazer",
      "Vanguard"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_nunu/hud/tft17_nunu_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_nunu/skins/base/images/tft17_nunu_splash_tile_35.tft_set17.png"
  },
  {
    "id": "rammus",
    "apiName": "TFT17_Rammus",
    "name": "Rammus",
    "cost": 4,
    "traits": [
      "Meeple",
      "Bastion"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_rammus/hud/tft17_rammus_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_rammus/skins/base/images/tft17_rammus_splash_tile_17.tft_set17.png"
  },
  {
    "id": "riven",
    "apiName": "TFT17_Riven",
    "name": "Riven",
    "cost": 4,
    "traits": [
      "Timebreaker",
      "Rogue"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_riven/hud/tft17_riven_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_riven/skins/base/images/tft17_riven_splash_tile_18.tft_set17.png"
  },
  {
    "id": "tahmkench",
    "apiName": "TFT17_TahmKench",
    "name": "Tahm Kench",
    "cost": 4,
    "traits": [
      "Oracle",
      "Brawler"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_tahmkench/hud/tft17_tahmkench_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_tahmkench/skins/base/images/tft17_tahmkench_splash_tile_11.tft_set17.png"
  },
  {
    "id": "galio",
    "apiName": "TFT17_Galio",
    "name": "The Mighty Mech",
    "cost": 4,
    "traits": [
      "Mecha",
      "Voyager"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_galio/hud/tft17_galio_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_galio/skins/base/images/tft17_galio_mobile.tft_set17.png"
  },
  {
    "id": "xayah",
    "apiName": "TFT17_Xayah",
    "name": "Xayah",
    "cost": 4,
    "traits": [
      "Stargazer",
      "Sniper"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_xayah/hud/tft17_xayah_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_xayah/skins/base/images/tft17_xayah_splash_tile_1.tft_set17.png"
  },
  {
    "id": "bard",
    "apiName": "TFT17_Bard",
    "name": "Bard",
    "cost": 5,
    "traits": [
      "Meeple",
      "Conduit"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_bard/hud/tft17_bard_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_bard/skins/base/images/tft17_bard_splash_tile_8.tft_set17.png"
  },
  {
    "id": "blitzcrank",
    "apiName": "TFT17_Blitzcrank",
    "name": "Blitzcrank",
    "cost": 5,
    "traits": [
      "Party Animal",
      "Space Groove",
      "Vanguard"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_blitzcrank/hud/tft17_blitzcrank_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_blitzcrank/skins/base/images/tft17_blitzcrank_splash_tile_65.tft_set17.png"
  },
  {
    "id": "fiora",
    "apiName": "TFT17_Fiora",
    "name": "Fiora",
    "cost": 5,
    "traits": [
      "Divine Duelist",
      "Anima",
      "Marauder"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_fiora/hud/tft17_fiora_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_fiora/skins/base/images/tft17_fiora_splash_tile_51.tft_set17.png"
  },
  {
    "id": "graves",
    "apiName": "TFT17_Graves",
    "name": "Graves",
    "cost": 5,
    "traits": [
      "Factory New"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_graves/hud/tft17_graves_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_graves/skins/base/images/tft17_graves_splash_tile_18.tft_set17.png"
  },
  {
    "id": "jhin",
    "apiName": "TFT17_Jhin",
    "name": "Jhin",
    "cost": 5,
    "traits": [
      "Dark Star",
      "Eradicator",
      "Sniper"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_jhin/hud/tft17_jhin_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_jhin/skins/base/images/tft17_jhin_splash_tile_37.tft_set17.png"
  },
  {
    "id": "shen",
    "apiName": "TFT17_Shen",
    "name": "Shen",
    "cost": 5,
    "traits": [
      "Bulwark",
      "Bastion"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_shen/hud/tft17_shen_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_shen/skins/base/images/tft17_shen_splash_tile_49.tft_set17.png"
  },
  {
    "id": "sona",
    "apiName": "TFT17_Sona",
    "name": "Sona",
    "cost": 5,
    "traits": [
      "Commander",
      "Psionic",
      "Shepherd"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_sona/hud/tft17_sona_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_sona/skins/base/images/tft17_sona_splash_tile_17.tft_set17.png"
  },
  {
    "id": "vex",
    "apiName": "TFT17_Vex",
    "name": "Vex",
    "cost": 5,
    "traits": [
      "Doomer"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_vex/hud/tft17_vex_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_vex/skins/base/images/tft17_vex_splash_tile_10.tft_set17.png"
  },
  {
    "id": "zed",
    "apiName": "TFT17_Zed",
    "name": "Zed",
    "cost": 5,
    "traits": [
      "Galaxy Hunter"
    ],
    "portrait": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_zed/hud/tft17_zed_square.tft_set17.png",
    "splash": "https://raw.communitydragon.org/latest/game/assets/characters/tft17_zed/skins/base/images/tft17_zed_splash_tile_68.tft_set17.png"
  }
];
