import type { Contested } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN PERFORMANCE OVERLAY  —  DO NOT HAND-EDIT
//
// Regenerated by the data pipeline; any manual change here is overwritten:
//   • npm run import   — apply numbers from a hand-filled JSON (no API key)
//   • npm run refresh  — crawl the Riot API and recompute (needs RIOT_API_KEY)
//
// Overrides ONLY the four performance fields of each comp; all structural data
// (units, traits, carries, items…) stays hand-authored in comps.ts. An empty
// record means "use the seed numbers in comps.ts".
// ---------------------------------------------------------------------------

export interface CompStats {
  avgPlace: number;
  top4: number; // %
  first: number; // %
  contested: Contested;
  sampleSize: number;
}

export const COMP_STATS: Record<string, CompStats> = {
  "darkstar-karma": {
    "avgPlace": 2.44,
    "top4": 51.7,
    "first": 28.7,
    "contested": "severe",
    "sampleSize": 373
  },
  "meeple-reroll": {
    "avgPlace": 2.52,
    "top4": 47.7,
    "first": 23.3,
    "contested": "severe",
    "sampleSize": 176
  },
  "vanguard-vex": {
    "avgPlace": 2.34,
    "top4": 54.5,
    "first": 31.5,
    "contested": "severe",
    "sampleSize": 178
  },
  "marauder-yi-kindred": {
    "avgPlace": 2.41,
    "top4": 54.1,
    "first": 26.1,
    "contested": "high",
    "sampleSize": 111
  },
  "space-groove-snipers": {
    "avgPlace": 2.38,
    "top4": 61,
    "first": 20.7,
    "contested": "high",
    "sampleSize": 82
  },
  "replicator-nova-mf": {
    "avgPlace": 2.76,
    "top4": 44,
    "first": 16,
    "contested": "low",
    "sampleSize": 25
  },
  "brawler-reroll-gragas": {
    "avgPlace": 3.03,
    "top4": 24.1,
    "first": 3.4,
    "contested": "low",
    "sampleSize": 29
  }
};

export const STATS_UPDATED_AT: string | null = "2026-05-30T16:09:40.591Z";

export const STATS_SOURCE: string | null = "riot-api:na1";
