import type { Contested } from '../types';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN PERFORMANCE OVERLAY  —  DO NOT HAND-EDIT
//
// Regenerated by the data pipeline; any manual change here is overwritten:
//   • npm run import   — apply numbers from a hand-filled JSON (no API key)
//   • npm run refresh  — crawl the Riot API and recompute (needs RIOT_API_KEY)
//
// Overrides ONLY the four performance fields of each comp; all structural data
// (units, traits, carries, items…) stays hand-authored in comps.ts. An empty
// record means "use the seed numbers in comps.ts".
// ---------------------------------------------------------------------------

export interface CompStats {
  avgPlace: number;
  top4: number; // %
  first: number; // %
  contested: Contested;
  sampleSize: number;
}

export const COMP_STATS: Record<string, CompStats> = {
  "darkstar-karma": {
    "avgPlace": 2.42,
    "top4": 52.4,
    "first": 30.2,
    "contested": "severe",
    "sampleSize": 315
  },
  "meeple-reroll": {
    "avgPlace": 2.51,
    "top4": 47.4,
    "first": 22.4,
    "contested": "severe",
    "sampleSize": 152
  },
  "vanguard-vex": {
    "avgPlace": 2.31,
    "top4": 57.4,
    "first": 31.6,
    "contested": "severe",
    "sampleSize": 155
  },
  "marauder-yi-kindred": {
    "avgPlace": 2.49,
    "top4": 48.4,
    "first": 22.1,
    "contested": "high",
    "sampleSize": 95
  },
  "space-groove-snipers": {
    "avgPlace": 2.6,
    "top4": 49.4,
    "first": 16.9,
    "contested": "high",
    "sampleSize": 77
  },
  "replicator-nova-mf": {
    "avgPlace": 3,
    "top4": 34.4,
    "first": 9.4,
    "contested": "moderate",
    "sampleSize": 32
  }
};

export const STATS_UPDATED_AT: string | null = "2026-06-04T21:27:22.052Z";

export const STATS_SOURCE: string | null = "riot-api:na1";
