import type { BoardScore } from '../lib/theorycraft';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN THEORYCRAFT DISCOVERIES  —  DO NOT HAND-EDIT
//
// High-synergy 8-unit boards discovered by the deterministic combat model's
// trait-anchored beam search (src/lib/theorycraft). Regenerated by:
//   • npm run build:theorycraft
//
// Ranked by a blended score (trait DEPTH + top-2 carry DPS + top-3 frontline
// EHP). This is a CANDIDATE GENERATOR — the math proposes, the crawled Double Up
// ladder data validates — so treat novel boards as leads to test, not as a meta.
// ---------------------------------------------------------------------------

export const DISCOVERED_BOARDS: BoardScore[] = [
  {
    "units": [
      "Bel'Veth",
      "Fiora",
      "Briar",
      "Gwen",
      "Riven",
      "Fizz",
      "Kai'Sa",
      "Jhin"
    ],
    "cost": 25,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Primordian",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Eradicator",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 24.8,
    "carryPower": 1574.612,
    "frontPower": 13131,
    "score": 52.512,
    "suggestedCarry": "Jhin",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 1312.599,
    "suggestedEmblem": "Primordian"
  },
  {
    "units": [
      "Fiora",
      "Aurora",
      "Karma",
      "Jhin",
      "The Mighty Mech",
      "Meepsie",
      "Pyke",
      "Master Yi"
    ],
    "cost": 29,
    "activeTraits": [
      {
        "name": "Voyager",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Eradicator",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 23.6,
    "carryPower": 1574.612,
    "frontPower": 14139,
    "score": 52.432,
    "suggestedCarry": "Jhin",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 1312.599,
    "suggestedEmblem": "Voyager"
  },
  {
    "units": [
      "Fiora",
      "Master Yi",
      "Viktor",
      "Mordekaiser",
      "Jhin",
      "Aurelion Sol",
      "Bard",
      "Zoe"
    ],
    "cost": 30,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Eradicator",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 23.6,
    "carryPower": 1574.612,
    "frontPower": 13494.375,
    "score": 51.716,
    "suggestedCarry": "Jhin",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 1312.599,
    "suggestedEmblem": "Vanguard"
  },
  {
    "units": [
      "Fizz",
      "Briar",
      "Fiora",
      "Gwen",
      "Riven",
      "Talon",
      "Urgot",
      "Tahm Kench"
    ],
    "cost": 23,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Brawler",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 23.4,
    "carryPower": 1245.562,
    "frontPower": 14976,
    "score": 50.42,
    "suggestedCarry": "Fiora",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 779.948,
    "suggestedEmblem": "Anima"
  },
  {
    "units": [
      "Briar",
      "Fiora",
      "Gwen",
      "Riven",
      "Kai'Sa",
      "Talon",
      "Blitzcrank",
      "Nasus"
    ],
    "cost": 22,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Space Groove",
        "count": 3,
        "tierLevel": 2
      },
      {
        "name": "Vanguard",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Party Animal",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 25.4,
    "carryPower": 1142.45,
    "frontPower": 13401,
    "score": 49.81,
    "suggestedCarry": "Fiora",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 660.973,
    "suggestedEmblem": "Anima"
  },
  {
    "units": [
      "Urgot",
      "Fiora",
      "Tahm Kench",
      "Master Yi",
      "Bel'Veth",
      "Gragas",
      "Rek'Sai",
      "Briar"
    ],
    "cost": 22,
    "activeTraits": [
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Marauder",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Primordian",
        "count": 3,
        "tierLevel": 2
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 18,
    "carryPower": 1424.958,
    "frontPower": 16152.075,
    "score": 47.821,
    "suggestedCarry": "Fiora",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 892.314,
    "suggestedEmblem": "Anima"
  }
];

/** When the discovery search was last run. */
export const THEORYCRAFT_UPDATED_AT = "2026-06-04T23:10:42.151Z";
/** Provenance of the underlying unit math the search ran on. */
export const THEORYCRAFT_SOURCE = "cdragon:TFTSet17";
