import type { BoardScore } from '../lib/theorycraft';

// ---------------------------------------------------------------------------
// MACHINE-WRITTEN THEORYCRAFT DISCOVERIES  —  DO NOT HAND-EDIT
//
// High-synergy 8-unit boards discovered by the deterministic combat model's
// trait-anchored beam search (src/lib/theorycraft). Regenerated by:
//   • npm run build:theorycraft
//
// Ranked by a blended score (trait DEPTH + top-2 carry DPS + top-3 frontline
// EHP). This is a CANDIDATE GENERATOR — the math proposes, the crawled Double Up
// ladder data validates — so treat novel boards as leads to test, not as a meta.
// ---------------------------------------------------------------------------

export const DISCOVERED_BOARDS: BoardScore[] = [
  {
    "units": [
      "Fiora",
      "Master Yi",
      "Viktor",
      "Morgana",
      "Aurelion Sol",
      "Bard",
      "Mordekaiser",
      "Blitzcrank"
    ],
    "cost": 32,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Vanguard",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Dark Lady",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Party Animal",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 26,
    "carryPower": 1281.095,
    "frontPower": 14373,
    "score": 52.646,
    "suggestedCarry": "Fiora",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 779.948,
    "suggestedEmblem": "Dark Star"
  },
  {
    "units": [
      "Fiora",
      "Urgot",
      "Tahm Kench",
      "Pantheon",
      "Gnar",
      "Jhin",
      "Ezreal",
      "Samira"
    ],
    "cost": 25,
    "activeTraits": [
      {
        "name": "Sniper",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Timebreaker",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Eradicator",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 22.2,
    "carryPower": 1360.669,
    "frontPower": 15962.85,
    "score": 51.275,
    "suggestedCarry": "Jhin",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 1312.599,
    "suggestedEmblem": "Timebreaker"
  },
  {
    "units": [
      "Fizz",
      "Gwen",
      "Riven",
      "Kai'Sa",
      "Briar",
      "Fiora",
      "Shen",
      "Jhin"
    ],
    "cost": 28,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Timebreaker",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Bulwark",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Eradicator",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 24.6,
    "carryPower": 1257.557,
    "frontPower": 14157,
    "score": 50.81,
    "suggestedCarry": "Jhin",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 1312.599,
    "suggestedEmblem": "Timebreaker"
  },
  {
    "units": [
      "Aurelion Sol",
      "The Mighty Mech",
      "Urgot",
      "Fiora",
      "Morgana",
      "Bard",
      "Mordekaiser",
      "Zoe"
    ],
    "cost": 29,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Mecha",
        "count": 3,
        "tierLevel": 1
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Divine Duelist",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Dark Lady",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 22.4,
    "carryPower": 1197.726,
    "frontPower": 16347.6,
    "score": 50.545,
    "suggestedCarry": "Fiora",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 779.948,
    "suggestedEmblem": "Mecha"
  },
  {
    "units": [
      "Kai'Sa",
      "Fizz",
      "Riven",
      "Briar",
      "Talon",
      "Shen",
      "Ezreal",
      "Milio"
    ],
    "cost": 20,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Timebreaker",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Bulwark",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 28,
    "carryPower": 872.539,
    "frontPower": 9400.5,
    "score": 45.716,
    "suggestedCarry": "Kai'Sa",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 599.282,
    "suggestedEmblem": "Dark Star"
  },
  {
    "units": [
      "Corki",
      "Fizz",
      "Gwen",
      "Riven",
      "Kai'Sa",
      "Talon",
      "Shen",
      "Rammus"
    ],
    "cost": 26,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Meeple",
        "count": 3,
        "tierLevel": 1
      },
      {
        "name": "Timebreaker",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Bastion",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Bulwark",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 23.8,
    "carryPower": 1046.582,
    "frontPower": 11697.8,
    "score": 45.519,
    "suggestedCarry": "Corki",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 647.203,
    "suggestedEmblem": "Timebreaker"
  },
  {
    "units": [
      "Blitzcrank",
      "Mordekaiser",
      "Morgana",
      "Aurelion Sol",
      "Bard",
      "Zoe",
      "Cho'Gath",
      "Tahm Kench"
    ],
    "cost": 27,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Vanguard",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Brawler",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Party Animal",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Dark Lady",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 26,
    "carryPower": 627.131,
    "frontPower": 11763,
    "score": 44.296,
    "suggestedCarry": "Blitzcrank",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 370.017,
    "suggestedEmblem": "Arbiter"
  },
  {
    "units": [
      "Samira",
      "Ezreal",
      "Shen",
      "Riven",
      "Pantheon",
      "Gnar",
      "Xayah",
      "Tahm Kench"
    ],
    "cost": 25,
    "activeTraits": [
      {
        "name": "Sniper",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Timebreaker",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 3,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Bulwark",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 24.8,
    "carryPower": 713.854,
    "frontPower": 11709,
    "score": 43.759,
    "suggestedCarry": "Samira",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 417.228,
    "suggestedEmblem": "Brawler"
  },
  {
    "units": [
      "Kindred",
      "Maokai",
      "Tahm Kench",
      "Urgot",
      "Rek'Sai",
      "Bel'Veth",
      "Jinx",
      "Diana"
    ],
    "cost": 22,
    "activeTraits": [
      {
        "name": "Challenger",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "N.O.V.A.",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Marauder",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Primordian",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 20,
    "carryPower": 1185.047,
    "frontPower": 12097.35,
    "score": 43.317,
    "suggestedCarry": "Kindred",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 786.254,
    "suggestedEmblem": "Challenger"
  },
  {
    "units": [
      "Pyke",
      "Viktor",
      "Morgana",
      "Mordekaiser",
      "Bard",
      "Aurelion Sol",
      "Karma",
      "The Mighty Mech"
    ],
    "cost": 28,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Voyager",
        "count": 3,
        "tierLevel": 2
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Lady",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 25.6,
    "carryPower": 643.933,
    "frontPower": 10821.375,
    "score": 42.99,
    "suggestedCarry": "Pyke",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 428.256,
    "suggestedEmblem": "Voyager"
  },
  {
    "units": [
      "Morgana",
      "Bard",
      "Mordekaiser",
      "Viktor",
      "Zoe",
      "Gragas",
      "Tahm Kench",
      "Leona"
    ],
    "cost": 23,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Vanguard",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Arbiter",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Brawler",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Lady",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 25,
    "carryPower": 577.212,
    "frontPower": 11757.375,
    "score": 42.874,
    "suggestedCarry": "Morgana",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 318.746,
    "suggestedEmblem": "Arbiter"
  },
  {
    "units": [
      "Bel'Veth",
      "Briar",
      "Riven",
      "Fizz",
      "Kai'Sa",
      "Talon",
      "Rek'Sai",
      "Tahm Kench"
    ],
    "cost": 19,
    "activeTraits": [
      {
        "name": "Rogue",
        "count": 5,
        "tierLevel": 4
      },
      {
        "name": "Primordian",
        "count": 3,
        "tierLevel": 2
      },
      {
        "name": "Brawler",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 24.2,
    "carryPower": 867.441,
    "frontPower": 10219.5,
    "score": 42.784,
    "suggestedCarry": "Bel'Veth",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 379.692,
    "suggestedEmblem": "Challenger"
  },
  {
    "units": [
      "Nami",
      "Pantheon",
      "Tahm Kench",
      "Maokai",
      "Gnar",
      "Shen",
      "Ezreal",
      "Milio"
    ],
    "cost": 23,
    "activeTraits": [
      {
        "name": "Timebreaker",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Replicator",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Sniper",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Bulwark",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 21,
    "carryPower": 687.64,
    "frontPower": 13309.2,
    "score": 41.518,
    "suggestedCarry": "Nami",
    "suggestedCarryItems": [
      "Rabadon's Deathcap",
      "Jeweled Gauntlet",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 524.055,
    "suggestedEmblem": "Sniper"
  },
  {
    "units": [
      "Akali",
      "Maokai",
      "Pantheon",
      "Shen",
      "Riven",
      "Ezreal",
      "Tahm Kench",
      "Cho'Gath"
    ],
    "cost": 22,
    "activeTraits": [
      {
        "name": "Timebreaker",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "N.O.V.A.",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Bulwark",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 18.4,
    "carryPower": 778.167,
    "frontPower": 13309.2,
    "score": 39.673,
    "suggestedCarry": "Akali",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 507.481,
    "suggestedEmblem": "Marauder"
  },
  {
    "units": [
      "Gnar",
      "Pantheon",
      "Riven",
      "Ezreal",
      "Milio",
      "Tahm Kench",
      "Cho'Gath",
      "Lissandra"
    ],
    "cost": 17,
    "activeTraits": [
      {
        "name": "Timebreaker",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Sniper",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Replicator",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 20,
    "carryPower": 595.026,
    "frontPower": 12032.1,
    "score": 38.328,
    "suggestedCarry": "Gnar",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 340.222,
    "suggestedEmblem": "Sniper"
  },
  {
    "units": [
      "Milio",
      "Pantheon",
      "Tahm Kench",
      "Riven",
      "Ezreal",
      "Maokai",
      "Gragas",
      "Caitlyn"
    ],
    "cost": 19,
    "activeTraits": [
      {
        "name": "Timebreaker",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Fateweaver",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "N.O.V.A.",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 18.6,
    "carryPower": 604.421,
    "frontPower": 13043.475,
    "score": 38.13,
    "suggestedCarry": "Milio",
    "suggestedCarryItems": [
      "Rabadon's Deathcap",
      "Jeweled Gauntlet",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 533.286,
    "suggestedEmblem": "Replicator"
  },
  {
    "units": [
      "Aurelion Sol",
      "Mordekaiser",
      "Cho'Gath",
      "Tahm Kench",
      "Maokai",
      "Gragas",
      "Viktor",
      "Zoe"
    ],
    "cost": 21,
    "activeTraits": [
      {
        "name": "Conduit",
        "count": 4,
        "tierLevel": 3
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Dark Star",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Psionic",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 18.6,
    "carryPower": 531.323,
    "frontPower": 13043.475,
    "score": 37.52,
    "suggestedCarry": "Aurelion Sol",
    "suggestedCarryItems": [
      "Rabadon's Deathcap",
      "Jeweled Gauntlet",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 487.114,
    "suggestedEmblem": "Conduit"
  },
  {
    "units": [
      "Ezreal",
      "Pantheon",
      "Tahm Kench",
      "Maokai",
      "Rek'Sai",
      "Riven",
      "Briar",
      "Talon"
    ],
    "cost": 17,
    "activeTraits": [
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Timebreaker",
        "count": 3,
        "tierLevel": 2
      },
      {
        "name": "Rogue",
        "count": 3,
        "tierLevel": 2
      },
      {
        "name": "Primordian",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 16.6,
    "carryPower": 596.809,
    "frontPower": 12854.25,
    "score": 35.856,
    "suggestedCarry": "Ezreal",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 369.964,
    "suggestedEmblem": "Timebreaker"
  },
  {
    "units": [
      "Rammus",
      "Aatrox",
      "Maokai",
      "Tahm Kench",
      "Cho'Gath",
      "Gragas",
      "Ornn",
      "Jax"
    ],
    "cost": 20,
    "activeTraits": [
      {
        "name": "Bastion",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "Brawler",
        "count": 4,
        "tierLevel": 2
      },
      {
        "name": "N.O.V.A.",
        "count": 2,
        "tierLevel": 1
      },
      {
        "name": "Oracle",
        "count": 1,
        "tierLevel": 1
      },
      {
        "name": "Space Groove",
        "count": 1,
        "tierLevel": 1
      }
    ],
    "traitScore": 13.4,
    "carryPower": 568.853,
    "frontPower": 14128.2,
    "score": 33.838,
    "suggestedCarry": "Rammus",
    "suggestedCarryItems": [
      "Infinity Edge",
      "Last Whisper",
      "Giant Slayer"
    ],
    "suggestedCarryDps": 273.786,
    "suggestedEmblem": "Dark Star"
  }
];

/** When the discovery search was last run. */
export const THEORYCRAFT_UPDATED_AT = "2026-08-10T13:11:26.300Z";
/** Provenance of the underlying unit math the search ran on. */
export const THEORYCRAFT_SOURCE = "cdragon:TFTSet17";
